### ISSUE TITLE
If I input 0.2+0.3 and the result is .5 instead of 0.5, the leading 0 is lost

### ISSUE THREAD

**Issue by xiaojian520** [openai-php/client#104]

**Comment by xiaojian520** [comment]
But when I directly request the OpenAI API, it returns 0.Did you do any processing on it?

**Comment by xiaojian520** [comment]
> That's is an API issue. Not an API Client issue.
But when I directly request the OpenAI API, it returns 0.Did you do any processing on it?

**Comment by nunomaduro** [comment]
cc @gehrisandro

**Comment by gehrisandro** [comment]
@xiaojian520 I don't understand what's the issue here.

Could you provide steps to reproduce the issue?

**Comment by xiaojian520** [comment]
> @xiaojian520 I don't understand what's the issue here.
> 
> Could you provide steps to reproduce the issue?

When I enter 0.1+0.2 using your client to request a response, the leading 0 disappears and the result is returned as .3.
![image](https://user-images.githubusercontent.com/6177311/233012428-5c41d2da-4604-409c-9169-8f91c133122d.png)

However, when I directly request the openid interface by entering 0.1+0.2, the result obtained is 0.3.

**Comment by gehrisandro** [comment]
I was able to reproduce. This only happens when you are using the `toArray()` on the reponse: 
```php
$response->toArray()['choices'][0]['delta']
```

using the object works fine:
```php
$response->choices[0]->delta
```

Going to release a fix for this as soon as possible.
