### ISSUE TITLE
how format generate text 

### ISSUE THREAD

**Issue by muhaned85** [openai-php/client#105]
how formate generate text as code

**Comment by muhaned85** [comment]
how use like this code by php to format result 
<script>
 
            const md = markdownit({
            linkify: true,  
            highlight: function (str, lang) { 
                try {
                    return hljs.highlightAuto(str).value;
                } catch (e) { }
                return ""; // use external default escaping
            }
        });
    let e = document.getElementById("chat");
    var result = md.render("Here's a simple PHP function to subtract two numbers:\n\n```\nfunction subtract($num1, $num2) {\n  return $num1 - $num2;\n}\n```\n\nTo use this function, you would pass in two numbers as arguments like this:\n\n```\n$result = subtract(5, 3);\necho $result; // Output: 2\n```\n\nIn this example, the function subtracts 3 from 5 and returns the result, which is then stored in a variable called `$result`. The `echo` statement then displays the result on the screen.");
    e.innerHTML=result;

**Comment by debuggerone** [comment]
Here are 8 options:

1st learn javascript
2nd hire a developer
3rd ask chatgpt
4th google it
5th learn coding in general from tutorials
6th take a course on programming
7th go to stackoverflow
8th rtfm

highlight_string() for php code
