### ISSUE TITLE
JSONL file validation issue

### ISSUE THREAD

**Issue by gyaanesh** [openai-php/client#107]
I was trying to upload a JSON file 
my training file 
`{"prompt": "How does Kaxxxo generate revenue?", completion: Kamaao genera}`
throwing error - NOT A VALID JSONL(OBVIOUSLY)
I updated and tried to upload again 
`{"prompt": "How does Kaxxxo generate revenue?", "completion": "Kaxxxo genera....."}`

and the file uploaded successfully, I got the ID and then tried to create fine-tune         
`$response = $this->client->fineTunes()->create([])`
success got ft-ID
then         
`$this->client->fineTunes()->retrieve('ft-oKYmlzPMY_IDBPxLodaCrew');`

status => pending
and error => INVALID JSONL FILE ON LINE XX

that line was 
`{"prompt": "my promt", "completion": "blah blah called as" tik-tak-go" some more text"}`
obviously its not a valid file but its should be checked before uploading..

**Comment by gehrisandro** [comment]
Hi @gyaanesh 

In my opinion it is not the responsibility of the library to check that your file is valid.

But I do understand your confusion as the OpenAI API does catch some errors when uploading a file but ignores others. Nevertheless I think you should ask OpenAI to fix this on their end.
