### ISSUE TITLE
Bug in CreateStreamedResponseDelt class when using array_filter

### ISSUE THREAD

**Issue by AstonChenDev** [openai-php/client#126]
Hi there,

I've been using the CreateStreamedResponseDelt class, and I've identified what I believe to be a bug. Specifically, when calling the array_filter function within this class, the string "0" is being filtered out, which causes unexpected behavior when calculating certain values.

To reproduce the issue, you can use the following prompt: “whats the result of 100 * 10 ”  the StreamResponse should be 1000. However, the returning is 100, which is incorrect and seems related to the aforementioned bug.

I would greatly appreciate it if this issue could be looked into and resolved as soon as possible.

Please let me know if you need more information or if there is anything else I can do to assist in resolving this issue.

Thanks,

**Comment by pb30** [comment]
I believe https://github.com/openai-php/client/pull/108 should fix this, but no new version has been tagged

**Comment by gehrisandro** [comment]
New version has been tag now: https://github.com/openai-php/client/blob/main/CHANGELOG.md#v050-2023-05-24
