### ISSUE TITLE
use stream failed

### ISSUE THREAD

**Issue by jinhuashijie** [openai-php/client#127]
when i use stream , code like down 
$stream = $client->completions()->createStreamed([
        'model' => 'text-davinci-003',
        'prompt' => $prompt,
        'max_tokens' => 1000,
    ]);
foreach($stream as $response){
    // echo $response->choices[0]->text."<br>";
    echo $response->choices[0]->text;
    // var_dump($response);
    // echo $response.id;
}
i have to wait atleats 12 s 
why this problem?
where i did error?

**Comment by pb30** [comment]
Streaming should use:
```php
foreach($stream as $response){
   echo $response->choices[0]->delta->content;
}
```

**Comment by kevinquillen** [comment]
You need to ensure your php and webserver configuration allow for this.

See this thread for more information: https://github.com/openai-php/client/issues/100
