### ISSUE TITLE
In streaming response output, when a single character '0' is encountered, it will be converted to an empty string

### ISSUE THREAD

**Issue by HackerWand** [openai-php/client#128]
input prompt: An array composed of ten zeros

streaming response output: 
```javascript
const array = [, , , , , , , , , ];
```

![Jietu20230524-215807](https://github.com/openai-php/client/assets/12233185/1dbcf45e-578c-4176-893c-05311713707a)

**Comment by pb30** [comment]
What version of the library? Try upgrading to 0.5.0

**Comment by gehrisandro** [comment]
Make sure you are using the latest version (v0.5.1), because '0' was stripped out in versions below v0.5.0 and in v0.5.0 stream responses didn't work at all.
