### ISSUE TITLE
Allow for ^1.1.0 || ^2.0 of psr/http-message in composer.json

### ISSUE THREAD

**Issue by kevinquillen** [openai-php/client#130]
Newer versions of Symfony 6.2+ component(s) rely on psr/http-message 2.0, which is blocking the install of this package. Can we expand the version constraint please?

See: https://www.drupal.org/project/drupalci_testbot/issues/3362781

**Comment by gehrisandro** [comment]
Hi @kevinquillen 

Thanks for raising the issue. I've released a new version (0.5.2) which allows for psr/http-message ^2.0
