### ISSUE TITLE
Missing new line / line break on responses

### ISSUE THREAD

**Issue by perryputtiapps** [openai-php/client#135]
I have this snippet;

```php
$promptRequest = [
            'model' => env('OPENAI_MODEL'),
            'messages' => [
                ['role' => 'system', 'content' => 'You are helpful assistant'],
                ['role' => 'user', 'content' => "Create 3 paragraph description about ChatGPT"]
            ]
        ];

$stream = $client->chat()->createStreamed($promptRequest);

  foreach ($stream as $response) {
      $content = data_get($response, 'choices.0.delta.content');       
  }
```

I'm getting the streamed content correctly but it's missing new line characters. Is there a way to show the line breaks / new line in the response content?

**Comment by pb30** [comment]
I see newlines in my streamed responses. How are you displaying the content? If it's HTML you'll need to convert to `<br>`.


You can verify they are there with: `echo json_encode($response->choices[0]->delta->content)`

**Comment by jtomek** [comment]
Thanks, this is very helpful. :)
