### ISSUE TITLE
getErrorCode(): Return value must be of type ?string, int returned

### ISSUE THREAD

**Issue by KevinFairbanks** [openai-php/client#151]
Upgraded to v0.6.2 and seeing this error frequently (3x in every 10-12 calls)

TypeError: OpenAI\Exceptions\ErrorException::getErrorCode(): Return value must be of type ?string, int returned in /home/app/my.app/vendor/openai-php/client/src/Exceptions/ErrorException.php:48

**Comment by KevinFairbanks** [comment]
Upon further troubleshooting as the fail rate increased to every other attempt, I found that the exception that seems to be casing it is:
"That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists."

I changed my script to use $errorCode = (string) $e->getErrorCode(); on the exception catch so that it will force the error code to be a string all the time and not break the processing so that the loop and retry.

**Comment by hakkikonu** [comment]
same error while using` images()->create`

**Comment by gehrisandro** [comment]
According to the OpenAI documentation this should always be a string: https://github.com/openai/openai-openapi/blob/ec0b3953bfa08a92782bdccf34c1931b13402f56/openapi.yaml#L1591

Can you provide a sample request which leads to a numeric error code?

**Comment by gehrisandro** [comment]
Closed due to inactivity. Please reopen if this is still an issue for you.
