### ISSUE TITLE
Undefined array key "transient"

### ISSUE THREAD

**Issue by VitalijOd** [openai-php/client#158]
Since yesterday, I have been receiving an error when using the Whisper model:

Undefined array key "transient" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"transient\" at /vendor/openai-php/client/src/Responses/Audio/TranscriptionResponseSegment.php:56)

It seems that the API may no longer return the "transient" property.

**Comment by thoasty-dev** [comment]
Same problem here.

**Comment by klaja** [comment]
Obviously something changed in the OpenAI API, as a quickfix (to get the library working again) the following diff seems to work:

diff --git a/html/vendor/openai-php/client/src/Responses/Audio/TranscriptionResponseSegment.php b/html/vendor/openai-php/client/src/Responses/Audio/TranscriptionResponseSegment.php
index de31603..0294404 100644
--- a/html/vendor/openai-php/client/src/Responses/Audio/TranscriptionResponseSegment.php
+++ b/html/vendor/openai-php/client/src/Responses/Audio/TranscriptionResponseSegment.php
@@ -53,7 +53,7 @@ final class TranscriptionResponseSegment implements ResponseContract
             $attributes['avg_logprob'],
             $attributes['compression_ratio'],
             $attributes['no_speech_prob'],
-            $attributes['transient'],
+            isset($attributes['transient'])?$attributes['transient']:false,
         );
     }

**Comment by nunomaduro** [comment]
Can any of you make a pull request?

**Comment by KaracsonyMarton** [comment]
Same problem here.

**Comment by nunomaduro** [comment]
@KaracsonyMarton @klaja @VitalijOd @thoasty-dev Would be cool to have one of you doing a pull request, so we can tag a new release with it.

**Comment by thoasty-dev** [comment]
Thank you for your quick support Nuno, I just opened a PR

**Comment by nunomaduro** [comment]
Fixed on v0.6.3. Please consider talking with your bosses to sponsoring our work on GitHub sponsors, because having the availability to simply doing releases during the week is expensive.
