### ISSUE TITLE
Not issue but improvment

### ISSUE THREAD

**Issue by oitsuki** [openai-php/client#166]
When the gpt anwser the question we can have the question or a text added inside the result like :

**Question** :
Sans répéter la question dans la réponse, peux-tu me traduire en Francais et me donner 7 mots clefs SEO sans inclure de termes répétitifs. Ils doivent être séparés par une virgule (exemple : vaisselle, verres, couverts pour la catégorie couverts) concernant ce terme : iphone+14+pro+max+

**Response** : 
Traduction en français : iPhone 14 Pro MaxMots-clés SEO : smartphone, Apple, haut de gamme, technologie, appareil mobile, iOS, performance

**All this point must be removed added by gpt :** Traduction en français : iPhone 14 Pro MaxMots-clés SEO :

**Correct response :** smartphone, Apple, haut de gamme, technologie, appareil mobile, iOS, performance

It will be fine if we can have a function to have only the brut response without some point added by gpt.

Currently I do not find anything like this inside the library

**Comment by gehrisandro** [comment]
Hi @oitsuki 

I think this is out of scope of this library as it depends on your prompt and requirements how to modify the response. So this should live in your application logic.
