### ISSUE TITLE
Undefined array key "transient"

### ISSUE THREAD

**Issue by ofaws** [openai-php/client#167]
I constantly get this error from Whisper API:

![image](https://github.com/openai-php/client/assets/91540029/d5422f53-e49d-4880-8c47-3433b67ca211)

Does anyone know how to fix it?

**Comment by nunomaduro** [comment]
Are you using the latest version of our package?

**Comment by ofaws** [comment]
Currently I have v0.4.2. Will upgrade and check again. Thank you)

**Comment by SanderMuller** [comment]
@nunomaduro I got this error on `0.5.2`, upgraded to `0.5.3` but I am still getting it.

![image](https://github.com/openai-php/client/assets/9074391/72147a80-7adc-4f6d-8534-b2a3273fe937)

**Comment by ofaws** [comment]
Upgrading to 0.6.3 solved issue for me

**Comment by SanderMuller** [comment]
Ah, `openai-php/laravel` didn't want to upgrade past  `v0.5.3`. Not sure how tags vs releases work, but maybe the Laravel wrapper requires some releases @nunomaduro

**Comment by pb30** [comment]
`openai-php/laravel` also has v0.6.3 version which should require 0.6.3 of this library. You can require/upgrade them both with:

`composer require -W "openai-php/client:^v0.6.3" "openai-php/laravel:^v0.6.3"`

**Comment by nunomaduro** [comment]
You guys need to simply use the latest version of both the API Client and Laravel integration: `v0.6`.
