### ISSUE TITLE
Sample with functions return error.

### ISSUE THREAD

**Issue by Jonston** [openai-php/client#170]
Sample with functions call return error.
`Fatal error: Uncaught TypeError: OpenAI\Responses\Chat\CreateResponseMessage::__construct(): Argument #2 ($content) must be of type string, null given`

**Comment by pb30** [comment]
Are you on latest version (currently v0.6.4)?

**Comment by Jonston** [comment]
> Are you on latest version (currently v0.6.4)?

I refresh version.Thank you a lot!
