### ISSUE TITLE
Unexpected / incomplete response for transcribe audio

### ISSUE THREAD

**Issue by gidzr** [openai-php/client#173]
Hi folks

According to your response example, transcribe should provide a number of results in the segments subarray ($response->segments as $segment). For some reason I don't get any of these results using json_verbose on an mp3 speech recording.

(ref: https://github.com/openai-php/client#audio-resource)

I've looked into the response per OpenAi (https://platform.openai.com/docs/api-reference/audio/create), but there's not a lot on the expected full response.

Has the openAi response changed, is it the openai-php api? or does the json_verbose response depend on the length of the audio recording?

Thanks

**Comment by gehrisandro** [comment]
Hi @gidzr 

Using exactly the example from the documentation I do receive a response containing segments.

Can you provide an example how to reproduce the issue?

**Comment by gehrisandro** [comment]
Closed due to inactivity. Please reopen if this is still an issue for you.
