### ISSUE TITLE
Retrieve RateLimits

### ISSUE THREAD

**Issue by krio-rogue** [openai-php/client#176]
Hi.
When requesting `https://api.openai.com/v1/chat/completions` in streaming mode, the HTTP response contains a set of headers with service information like `X-Ratelimit-Remaining-Tokens:`.

Is it possible to add a method to retrieve all headers from stream? 
Or make the `$response` property in the `OpenAI\Responses\StreamResponse` class public?

**Comment by Jafo232** [comment]
I agree.  We need this for things like calculating how many tokens were used.

**Comment by Jafo232** [comment]
I submitted this PR that would accomplish this:  https://github.com/openai-php/client/pull/187

**Comment by gehrisandro** [comment]
You can now use the [latest release](https://github.com/openai-php/client/releases/tag/v0.7.0) which gives you access to the header / meta information on every response: https://github.com/openai-php/client#meta-information
