### ISSUE TITLE
Does this support Azure OpenAI with your own data?

### ISSUE THREAD

**Issue by bocanhcam** [openai-php/client#180]
This might be really a stupid question but I am a newbie to this world of AI service, so

Is there any config need to do to make this package work with Azure OpenAI using my own data?

**Comment by iBotPeaches** [comment]
Presuming I understand your question. You deploy a model into Azure, you get a deploymentId from that. You use it in the base url of configuring your Azure implementation. So yes if thats what you mean.

See this: https://github.com/openai-php/client#azure
