### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by fulldecent** [openai-php/client#185]
May GitHub releases please be used for this project?

**Comment by gehrisandro** [comment]
Good input. Thank you!

**Comment by fulldecent** [comment]
Thank you. I do not see the releases in GitHub.

Here is what releases look like.

<img width="1485" alt="Screenshot 2023-08-15 at 11 42 41" src="https://github.com/openai-php/client/assets/382183/c9d6d340-bcaa-43ef-a6f6-643035747cf9">

And FYI, if you use releases it allows people to subscribe for email updates. Which helps you meet the project goals.

**Comment by vesper8** [comment]
Releases are accessible for this project, they are, for some reason, just not displayed in the sidebar

https://github.com/openai-php/client/releases

Is this on purpose @gehrisandro @nunomaduro ?
