### ISSUE TITLE
Get token count at end of stream

### ISSUE THREAD

**Issue by Jafo232** [openai-php/client#186]
Consider:

```
$stream = $this->client->chat()->createStreamed([
                                                      'model' => config('services.openai.model'),
                                                      'messages' => $prompts,

                                                  ]);

  foreach ($stream as $response) {

      $this->response .= $response->choices[0]->delta->content;

  }

```

            
How do I get access to the tokens used after all of this is done?  The response property is private.

**Comment by Jafo232** [comment]
I submitted this PR that would make this work.

https://github.com/openai-php/client/pull/187

**Comment by gehrisandro** [comment]
You can now use the [latest release](https://github.com/openai-php/client/releases/tag/v0.7.0) which gives you access to the header / meta information on every response: https://github.com/openai-php/client#meta-information

**Comment by georgesma** [comment]
> You can now use the [latest release](https://github.com/openai-php/client/releases/tag/v0.7.0) which gives you access to the header / meta information on every response: https://github.com/openai-php/client#meta-information

I have the same problem. I've tried to use the meta information but it doesn't give information about usage (eg. `promptTokens`, `completionTokens`, `totalTokens`).

**Comment by Jafo232** [comment]
But this doesn't tell you how many input/output tokens were used unless I am missing something..

**Comment by georgesma** [comment]
> But this doesn't tell you how many input/output tokens were used unless I am missing something..

I just found out that this is due to an OpenAI API limitation, not to the PHP implementation.
Source: https://cookbook.openai.com/examples/how_to_stream_completions#downsides

> _Another small drawback of streaming responses is that the response no longer includes the usage field to tell you how many tokens were consumed. After receiving and combining all of the responses, you can calculate this yourself using [tiktoken](https://cookbook.openai.com/examples/How_to_count_tokens_with_tiktoken.ipynb)._
