### ISSUE TITLE
completions create: support stream?

### ISSUE THREAD

**Issue by gehrisandro** [openai-php/client#19]
see: https://beta.openai.com/docs/api-reference/completions/create#completions/create-stream

should we support stream response?

**Comment by bergsten** [comment]
I'm very interested in the stream response functionality, so I'm voting for it to be implemented.

**Comment by isotropicdesign** [comment]
+1 - This would be a great addition.

**Comment by nunomaduro** [comment]
@gehrisandro What would this represent in terms of code changes?

**Comment by orhanerday** [comment]
I added today to @orhanerday/open-ai You can copy it from my repo :)

**Comment by orhanerday** [comment]
@nunomaduro I added today to @orhanerday/open-ai You can copy it from my repo :)

**Comment by slavarazum** [comment]
In [the current draft](https://github.com/openai-php/client/pull/21) we trying to save the same [`CreateResponse`](https://github.com/openai-php/client/blob/main/src/Responses/Completions/CreateResponse.php) object which allows to iterate over himself when stream response was requested.

**Comment by utfd** [comment]
I switch this package instead https://github.com/orhanerday/open-ai#stream-example

**Comment by CaReS0107** [comment]
@nunomaduro some news on this functionality (Streaming)
