### ISSUE TITLE
Comile error

### ISSUE THREAD

**Issue by Ronaldo-F-dev** [openai-php/client#197]
Who can help me ? I have this message when i try to use this package.
Compile Error: Cannot declare class OpenAI, because the name is already in use

**Comment by pb30** [comment]
Do you have any other OpenAI packages installed? Can you share your composer.json? Did you create your own OpenAI class?

**Comment by iBotPeaches** [comment]
This class doesn't have a namespace so OpenAI is reserved once its installed - https://github.com/openai-php/client/blob/main/src/OpenAI.php

So yeah either this package should namespace that to OpenAI/OpenAI or you have to find what else is using that class name and remove it.

**Comment by gehrisandro** [comment]
@Ronaldo-F-dev @iBotPeaches 

It is intended to have no namespace here.

Therefore you have to look where your conflicting class comes from.
