### ISSUE TITLE
Typo in `OpenAI\Responses\Meta\MetaInformaionOpenAI`

### ISSUE THREAD

**Issue by eliashaeussler** [openai-php/client#200]
Hey,

first, thanks for this great piece of code :tada:

I found a typo in the latest release. See https://github.com/openai-php/client/blob/v0.7.0/src/Responses/Meta/MetaInformaionOpenAI.php#L5 → I believe it should be `MetaInformationOpenAI` instead.

```diff
-final class MetaInformaionOpenAI
+final class MetaInformationOpenAI
```

**Comment by gehrisandro** [comment]
Thx @eliashaeussler 

Fixed in v0.7.1
