### ISSUE TITLE
Streamed Response With Functions

### ISSUE THREAD

**Issue by jbainpro** [openai-php/client#202]
When using Functions with chat()->createStreamed the function call name and argument is not returned. I see on the OpenAI docs that it should be returned in the stream as well. Can anyone offer some guidance as to why it isn't being returned. It works fine with chat()->create or when the second call is made but I want the response of the first call to be streamed back if no function is called.

**Comment by jbainpro** [comment]
Figured it out, it was my mistake.

**Comment by JibayMcs** [comment]
> Figured it out, it was my mistake.

Hi ! 

I'm facing the same issue, how did you manage this behaviour ?

Thanks in advance ! :D
