### ISSUE TITLE
Feature request: gpt-3.5-turbo-instruct model

### ISSUE THREAD

**Issue by mycloudvip** [openai-php/client#211]
With today's announcement of the gpt-3.5-turbo-instruct model, will it be included or be compatible with this script?

If so, kindly provide code example on how to use access it or setup my PHP code to support it.

Thanks

**Comment by gehrisandro** [comment]
Yes the library is fully compatible because the API itself does not change. You can use it with the [completion resource](https://github.com/openai-php/client#completions-resource), just provide the new model name.
