### ISSUE TITLE
Undefined array key "openai-processing-ms"

### ISSUE THREAD

**Issue by DC-Sebastian** [openai-php/client#218]
I am trying to use the AI provider [Anyscale](https://docs.endpoints.anyscale.com/guides/migrate-from-openai), which provides Metas Llama-2 models and returns them in the same structure as Open AI. With the official Python Open AI library this is possible by simply setting the OPENAI_API_BASE URI to https://api.endpoints.anyscale.com/v1.

When I try to use the base uri api.endpoints.anyscale.com/v1 with openai-php I get the error message:
`Undefined array key "openai-processing-ms" in C:\xampp\htdocs\chatgpt\vendor\openai-php\client\src\Responses\Meta\MetaInformation.php on line 37`

Any idea what could be causing this?

Here is the code I use for this:
`$client = OpenAI::factory()
    ->withApiKey($yourApiKey)
    ->withBaseUri('api.endpoints.anyscale.com/v1')
    ->make();`

**Comment by pb30** [comment]
This library expects a `"openai-processing-ms"` header in the response, but Anyscale does not include one

**Comment by DC-Sebastian** [comment]
Is there a possibility to remove the dependency for the header?
The possibility of being able to use the Lama 2 models is quite useful.

**Comment by sstalle** [comment]
@DC-Sebastian You can add the header to a response before it is processed by the library. The exact way to do this would depend on the HTTP client you are using. Here is a quick example for [Guzzle](https://docs.guzzlephp.org/en/stable/overview.html):
```
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use Psr\Http\Message\ResponseInterface;

$stack = HandlerStack::create();
$stack->push(
    Middleware::mapResponse(function (ResponseInterface $response) {
        return $response->withHeader('openai-processing-ms', '1');
    })
);
$guzzle = new Client(['handler' => $stack]);

$yourApiKey = '...';
$client = \OpenAI::factory()
    ->withApiKey($yourApiKey)
    ->withBaseUri('api.endpoints.anyscale.com/v1')
    ->withHttpClient($guzzle)
    ->make();
```

**Comment by bianchi** [comment]
This started happening for me too. I'm using Azure OpenAi.

**Comment by rkgo55** [comment]
Hello.
I also got the same error when using Azure OpenAi.
I think the problem occurs when sending consecutive requests.
