### ISSUE TITLE
Fine-Tuning n_epochs can be a string or integer

### ISSUE THREAD

**Issue by vestaxpdx** [openai-php/client#225]
Hi

From the openai documentation n_epochs can be a string or integer.

https://platform.openai.com/docs/api-reference/fine-tuning/create

> n_epochs string or integer Optional Defaults to auto

This is causing the client to bug out if it has been set at 'auto' when returning a list of jobs or if we try and create a job with n_epochs as 'auto' because in the code base it's been set as an integer only.

**Comment by gehrisandro** [comment]
Fixed in https://github.com/openai-php/client/releases/tag/v0.7.4

Thanks for reporting!
