### ISSUE TITLE
Where to modify to adapt a locally-deployed OpenAI API compatible service?

### ISSUE THREAD

**Issue by fishfree** [openai-php/client#226]
This package is very productive. Thank you for your great work!
I'd like to modfiy some codes to use a locally-deployed  OpenAI API compatible service in our university. I don't konw which files to modify to make it, it's beyond my capability. Any help would be apprciately very much!

**Comment by gehrisandro** [comment]
Hi @fishfree 

Probably it is enough to change the URL by using the factory:

```php
$client = OpenAI::factory()
    ->withApiKey($yourApiKey)
    ->withBaseUri($yourLocalUrl) // default: api.openai.com/v1
    ->make();
