### ISSUE TITLE
Job Event Data seems to have a changed structure

### ISSUE THREAD

**Issue by axelbecher** [openai-php/client#227]
the format I get via OpenAI Api is 

```
{
    "error_code": "invalid_n_examples",
    "error_param": "training_file"
}
```
Leading to an Exception in ListJobEventsResponseEvent as the line

`$attributes['data'] ? ListJobEventsResponseEventData::from($attributes['data']) : null,`

fails as ListJobEventsResponseEventData expects a different structure:

```
$attributes['step'],
$attributes['train_loss'],
$attributes['train_mean_token_accuracy'],
```

**Comment by gehrisandro** [comment]
Hi @axelbecher 

To me it looks like your request is invalid.

But if not, can you provide some code to reproduce the error?

**Comment by axelbecher** [comment]
Hello @gehrisandro, I do a normal list JobEvents request like

**Comment by axelbecher** [comment]
@gehrisandro I hotfixed above problem with an additional check

```
public static function from(array $attributes): self
    {
        return new self(
            $attributes['object'],
            $attributes['id'],
            $attributes['created_at'],
            FineTuningEventLevel::from($attributes['level']),
            $attributes['message'],
            $attributes['data'] && array_key_exists('step', $attributes['data']) ? ListJobEventsResponseEventData::from($attributes['data']) : null,
            $attributes['type'],
        );
    }
```
As it seems there are now different JobListEvent formats coming from OpenAI

**Comment by axelbecher** [comment]
Thanks for investigating!

**Comment by gehrisandro** [comment]
@axelbecher This seems strange to me. You fix looks like "step" is missing but the error you originally posted was about an error in the training file.

Could you please provide a raw JSON response which causes the error with the step?

**Comment by axelbecher** [comment]
Hello @gehrisandro,
sorry for the late reply and the little bit unstructured communication until here, I was in the middle of a bigger Feature-Release ;-)

**Comment by axelbecher** [comment]
To trigger the Problem, I simply fetch the Job-Events for a failed Job with the Client, just like
$openAiClient->fineTuning()->listJobEvents('ftjob-XXXXXXXXXXXXXXXXXXX');

**Comment by axelbecher** [comment]
The raw result will look like:

```
{
  "object": "list",
  "data": [
    {
      "object": "fine_tuning.job.event",
      "id": "ftevent-XXXXXXXXXXXXXXXXXXXXXX",
      "created_at": 1698074763,
      "level": "error",
      "message": "Training file has 6 example(s), but must have at least 10 examples",
      "data": {
        "error_code": "invalid_n_examples",
        "error_param": "training_file"
      },
      "type": "message"
    },
    {
      "object": "fine_tuning.job.event",
      "id": "ftevent-XXXXXXXXXXXXXXXXXXXX",
      "created_at": 1698074740,
      "level": "info",
      "message": "Validating training file: file-XXXXXXXXXXXXXXXXXXXX",
      "data": {},
      "type": "message"
    },
    {
      "object": "fine_tuning.job.event",
      "id": "ftevent-XXXXXXXXXXXXXXXXXXXX",
      "created_at": 1698074740,
      "level": "info",
      "message": "Created fine-tuning job: ftjob-XXXXXXXXXXXXXXXXXXXX",
      "data": {},
      "type": "message"
    }
  ],
  "has_more": false
}
```

**Comment by axelbecher** [comment]
The Event data

```
      {
        "error_code": "invalid_n_examples",
        "error_param": "training_file"
      }
```
Leads to the afromentioned Bug in the Client:

`$attributes['data'] ? ListJobEventsResponseEventData::from($attributes['data'])`

in **ListJobEventsResponseEvent**

expects as follows in **ListJobEventsResponseEventData**

```
    public static function from(array $attributes): self
    {
        return new self(
            $attributes['step'],
            $attributes['train_loss'],
            $attributes['train_mean_token_accuracy'],
        );
    }
```

**Comment by axelbecher** [comment]
I Maybe the problem occures because the error originates from the file and not the training itself ? Anyway, to simple exclude it from the Client result would be sufficient I think as it does not add anything meaningful to the event itself...
Thanks for taking a look into this!

**Comment by gehrisandro** [comment]
I am not sure if this problem still exists.

With the latest release (v0.7.10) errors are handled instead of ignored.

But what me still confuses is your json example. In my case I receive a different json structure. May OpenAI has changed something on their side.

If you are still able to reproduce the issue. Please feel free to reopen the issue. And if possible, please provide a full request sequence (JobCreate and JobList) to reproduce the issue.

**Comment by axelbecher** [comment]
Hello @gehrisandro,

The problem still exists but it causes no Exception anymore, just warnings. You can provoke it by uploading an invalid trainings-file with less than the mandatory 10 examples. I do a file-upload immediately followed with the job creation, to check the state of the training I list the job-events the returned responses are as follows:

```
$this->client->fineTuning()->createJob($jobProps) RESPONSE: 
{
  "object": "fine_tuning.job",
  "id": "ftjob-XXXXXXXXXXXXXXXXXXXX",
  "model": "gpt-3.5-turbo-0613",
  "created_at": 1700127162,
  "finished_at": null,
  "fine_tuned_model": null,
  "organization_id": "org-XXXXXXXXXXXXXXXXXXXX",
  "result_files": [],
  "status": "validating_files",
  "validation_file": null,
  "training_file": "file-XXXXXXXXXXXXXXXXXXXX",
  "hyperparameters": {
    "n_epochs": "auto",
    "batch_size": "auto",
    "learning_rate_multiplier": "auto"
  },
  "trained_tokens": null,
  "error": null
}

$openAiClient->fineTuning()->listJobEvents($jobId) RESPONSE:
{
  "object": "list",
  "data": [
    {
      "object": "fine_tuning.job.event",
      "id": "ftevent-XXXXXXXXXXXXXXXXXXXX",
      "created_at": 1700127173,
      "level": "error",
      "message": "Training file has 5 example(s), but must have at least 10 examples",
      "data": {
        "error_code": "invalid_n_examples",
        "error_param": "training_file"
      },
      "type": "message"
    },
    {
      "object": "fine_tuning.job.event",
      "id": "ftevent-XXXXXXXXXXXXXXXXXXXX",
      "created_at": 1700127162,
      "level": "info",
      "message": "Validating training file: file-XXXXXXXXXXXXXXXXXXXX",
      "data": {},
      "type": "message"
    },
    {
      "object": "fine_tuning.job.event",
      "id": "ftevent-XXXXXXXXXXXXXXXXXXXX",
      "created_at": 1700127162,
      "level": "info",
      "message": "Created fine-tuning job: ftjob-XXXXXXXXXXXXXXXXXXXX",
      "data": {},
      "type": "message"
    }
  ],
  "has_more": false
}
PHP Warning:  Undefined array key "step" in /vendor/openai-php/client/src/Responses/FineTuning/ListJobEventsResponseEventData.php on line 35
PHP Warning:  Undefined array key "train_loss" in /vendor/openai-php/client/src/Responses/FineTuning/ListJobEventsResponseEventData.php on line 36
PHP Warning:  Undefined array key "train_mean_token_accuracy" in /vendor/openai-php/client/src/Responses/FineTuning/ListJobEventsResponseEventData.php on line 37
```
