### ISSUE TITLE
TypeError: OpenAI::client(): Argument #1 ($apiKey) must be of type string, null given

### ISSUE THREAD

**Issue by bardolf69** [openai-php/client#228]
```$oaClient = \OpenAI::client('sk-*****************************N');``` obviously I've removed most of the API key but I have verified that the key is valid and active.  I am running v0.7.4.  Does anyone have any ideas where I can start looking?

**Comment by gehrisandro** [comment]
@bardolf69 This looks strange to me, as you pass a string and not null. Probably there is something else wrong in your call.

Maybe a complete stack trace would help.
