### ISSUE TITLE
Value object and arguments with the name `ApiToken|$apiToken` should be `ApiKey|$apiKey`

### ISSUE THREAD

**Issue by nunomaduro** [openai-php/client#23]
We've just noticed that, within this project, we are using the terminology `ApiToken` and `$apiToken`, where in fact, it should `ApiKey` and `$apiKey`, as mentioned in multiple places in OpenAI documention.

**Comment by filips-dev** [comment]
@nunomaduro Seeing as I'm new to Open source how can I push my branch and make a PR?

**Comment by nunomaduro** [comment]
Fixed here: https://github.com/openai-php/client/pull/25.
