### ISSUE TITLE
permissions object in models -> retrieve seems now optional leading to exceptions in client

### ISSUE THREAD

**Issue by axelbecher** [openai-php/client#231]
It seems since today the permissions data is optional or even gone, see this forum post:

https://community.openai.com/t/missing-permission-inside-model-response/470014

It is also gone from the official API-reference now:

https://platform.openai.com/docs/api-reference/models/object

Their API seems to change quickly and without notice ...

**Comment by gehrisandro** [comment]
A fix will be released soo: https://github.com/openai-php/client/pull/235
