### ISSUE TITLE
Support for the latest OpenAI release

### ISSUE THREAD

**Issue by arndvs** [openai-php/client#240]
I realize the new release just came out yesturday, but commenting here to be notified when the new OpenAI library is addeed to make calls to gpt-4-turbo with and without streaming, new function calling, image generation api with dall-e-3, GPT 4 Vision API, text to speech API, and Assistants API.

**Comment by gehrisandro** [comment]
@arndvs You can watch the repository, no issue needed for that.

By the way, some of the features are already implemented: https://github.com/openai-php/client/blob/main/CHANGELOG.md

**Comment by arndvs** [comment]
ah awesome - fantastic work! Thanks

**Comment by arndvs** [comment]
@gehrisandro - one question, are you aware of any breaking changes with the new api and models?

**Comment by gehrisandro** [comment]
As far as I know, there are no breaking changes. There are some deprecations, but for now everything should work.
