### ISSUE TITLE
Typo in Community Libraries Section of Documentation

### ISSUE THREAD

**Issue by iscjesusmartinez** [openai-php/client#250]
## Description
There is a small typo in the Community Libraries section of the OpenAI API documentation. The word "client" is misspelled as "clinet" under the PHP libraries.

## Screenshot
[https://user-images.githubusercontent.com/1821195/282232776-b79e7899-64e0-4632-9f16-0cf870fd2362.png](url)

## Steps to Reproduce
1. Go to the [Community Libraries page](https://platform.openai.com/docs/libraries/community-libraries).
2. Scroll down to the PHP section.
3. Observe the typo in the text "openai-php clinet".

## Expected Behavior
The text should read "openai-php client".

## Actual Behavior
The text currently reads "openai-php clinet".

I've created this issue to help improve the documentation by correcting this typo. Thank you for maintaining such comprehensive documentation for the community.

**Comment by nunomaduro** [comment]
Can you report this to the OpenAI documentation team instead?
