### ISSUE TITLE
SOLVED: Add support for the "response_format"-param in a chat completion call

### ISSUE THREAD

**Issue by axelbecher** [openai-php/client#251]
Please add support for the "response_format"-param in a chat completion call, which currently leads to an exception:  Unrecognized request argument supplied: response_format

**Comment by axelbecher** [comment]
OpenAI added it on the dev-day:
https://platform.openai.com/docs/api-reference/chat/create

**Comment by gehrisandro** [comment]
Hi @axelbecher 

According to the docs, this is a request-only attribute. So there should be nothing we have to change from our side.
But maybe the docs are wrong.

Could you please provide an example of a failing request?

**Comment by axelbecher** [comment]
Hi @gehrisandro,
indeed, you are correct, this Exception was generated on their side when requesting a "non-1106" model with this param. Sorry, I thought it's coming from the Client ;-) That's realy an annoyance of the OpenAI API, they should make an endpoint with the capabilities, a model has (frame-size, supported response formats, trainability ...)
