### ISSUE TITLE
Can I help with Assistants?

### ISSUE THREAD

**Issue by rodrigonsh** [openai-php/client#254]
Hi Nuno and Sandro, I would like to add a chat to my personal website with an Assistant I made in Playground but I just cant find something like that in the repo

I would like to offer my skills to help implement this but i'm no programming god, so can you help somehow pointing me to classes and docs I should refer to?

Please consider my request
Thanks in advance

**Comment by jason-engage** [comment]
Somebody needs to use chatGPT to quickly build the classes we need for assistants functionality...

**Comment by LMCom** [comment]
FYI, here is the branch: https://github.com/openai-php/client/tree/add-assistant-api
@gehrisandro Seems to be very busy working on it.

**Comment by gehrisandro** [comment]
The release is out: https://x.com/gehrisandro/status/1724046187957715103?s=20
