### ISSUE TITLE
gpt-4-vision-preview - receives an incomplete response

### ISSUE THREAD

**Issue by shakhbiev** [openai-php/client#260]
After sending an image, I receive an incomplete response in the “content” key

```
(
    [index] => 0
    [message] => OpenAI\Responses\Chat\CreateResponseMessage Object
        (
            [role] => assistant
            [content] => The image shows a Nikon DSLR camera with a telephoto lens attached, resting
            [toolCalls] => Array
                (
                )
            [functionCall] => 
        )
    [finishReason] => 
)
```

Why is the answer text cut?

**Comment by ThibautPV** [comment]
I think your 'max_tokens' is too low.

Increase the 'max_tokens' value to 900 (for example) like this: 'max_tokens' => 900.

**Comment by sevenpixels** [comment]
@shakhbiev I see you are getting a response. Can you share your code? I keep getting an error when sending the request with the library but not with CURL ... same request. #258

**Comment by gehrisandro** [comment]
@shakhbiev I agree with @ThibautPV

**Comment by shakhbiev** [comment]
> @shakhbiev I agree with @ThibautPV

No. I added max_tokens=1000, but the problem is still solved. Now I checked, even without specifying max_tokens everything works, I get the full text

**Comment by shakhbiev** [comment]
Perhaps the problem was on the OpenAI side

**Comment by shakhbiev** [comment]
> @shakhbiev I agree with @ThibautPV

Yes, problem solved!
