### ISSUE TITLE
It's very slow and there are frequent errors

### ISSUE THREAD

**Issue by shakhbiev** [openai-php/client#266]
Requests are processed very slowly and almost every third request ends in an error:

`Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\HttpClient\\Exception\\TimeoutException: Idle timeout reached for`

Why is everything working so poorly?

I see how in other projects the API works instantly and without failures.

**Comment by gehrisandro** [comment]
Depending on the model you are using, OpenAI has a lot of issues the last couple of days. Especially with the Assistants API.

https://status.openai.com/

But the PHP client has no influence on that.
