### ISSUE TITLE
limit on 32 messages

### ISSUE THREAD

**Issue by kaemmi84** [openai-php/client#269]
`$messages = Message
                ::where('role', 'user')
                //->where('user_id', Auth::id())
                ->orderBy('created_at', 'asc')
                ->select(['role', 'content'])
                ->get()
                ->map(function (mixed $item) {
                    return [
                        'role' => $item->role,
                        'content' => $item->content,
                    ];
                });

            //throw new Exception(json_encode($messages));

            $response = $this->openAIClient->threads()->createAndRun(
                [
                    'assistant_id' => $this->assistantId,
                    'thread' => [
                        'messages' => $messages,
                    ],
                ],
            );`

on this code I became the error 

OpenAI\Exceptions\ErrorException: 1 validation error for Request
body -&gt; thread -&gt; messages
  ensure this value has at most 32 items (type=value_error.list.max_items; limit_value=32) in file /var/www/kaemmi/vendor/openai-php/client/src/Transporters/HttpTransporter.php on line 131

**Comment by gehrisandro** [comment]
Hi @kaemmi84 

This is an error / limit from the OpenAI API. There is nothing the PHP client could do about this.
