### ISSUE TITLE
How can I execute runs with exististing thread

### ISSUE THREAD

**Issue by kaemmi84** [openai-php/client#270]
`public function postMessage($user, $content, $role)
    {
        $this->getOrCreateThreat();
        $now = Carbon::now();
        //create user content
        $response = $this->openAIClient->threads()->messages()->create($this->threadId, [
            'role' => $role,
            'content' => "$now:::\n\n {$content}",

        ]);
        foreach ($response->content as $content) {
            $message = new Message;
            $message->role = $response->role;
            $message->content = $content->text->value;
            $user->messages()->save($message);
        }

        //run thread
        $response = $this->openAIClient->threads()->?
    }`
    
    I don't find a function to run existing threads in the documentation
    
    EDIT: Ok I find $this->openAIClient->threads()->runs()->create how can I use this?

**Comment by gehrisandro** [comment]
Hi @kaemmi84 

You need to provide the thread_id. See: https://github.com/openai-php/client/tree/0.8.x#threads-runs-resource-beta

Hope this helps. Otherwise, let me know.

**Comment by kaemmi84** [comment]
Thanks but the question is how actuality the frontend. whithout waiting on the post endpoints. Work this with websockets?
