### ISSUE TITLE
[Bug]: composer update 0.8.0 error

### ISSUE THREAD

**Issue by ZhangKoven** [openai-php/client#272]
### Description

when i need to update openai-php/client to version 0.8.0,composer give me an error
Root composer.json requires openai-php/client 0.8.0, found openai-php/client[dev-fix-fine-tuning-job-response-hyperparameters-nEpochs-can-be-string, ..., dev-add-assistant-api, v0.1.0, ..., 0.8.x-dev] but it does not match the constraint.

### Steps To Reproduce

composer.json i set version 0.8.0
when i set version ^0.8.0,it run success.but the version is 0.8.0.beta.3

### OpenAI PHP Client Version

v0.8.0

### PHP Version

8.1.17

**Comment by gehrisandro** [comment]
Hi @ZhangKoven 

I am not able to reproduce the problem.

If the problem still persist, could you please provide your composer.json file?

**Comment by ZhangKoven** [comment]
"openai-php/client":"0.8.0" 
when i run composer openai-php/client update

**Comment by ZhangKoven** [comment]
this is my composer.json
[composer.json](https://github.com/openai-php/client/files/13456225/composer.json)

**Comment by gehrisandro** [comment]
I've used your composer.json file and it installed the correct version:

> Installing openai-php/client (v0.8.0): Extracting archive

**Comment by ZhangKoven** [comment]
Unbelievable，let me try anain on my test server

**Comment by ZhangKoven** [comment]
i try it on my test server,it run success.
but my vmware still run error

**Comment by ZhangKoven** [comment]
emmm, this question is my mistake.
my composer source is aliyun 
i forgot it
now, my vmware run success.
