### ISSUE TITLE
Get the ID of an assistant if we create it from the Open AI website

### ISSUE THREAD

**Issue by dec** [openai-php/client#273]
Hello to all,

Firstly, many thanks for your work on this library. I want to ask something not specifically related with the library, but, that maybe someone here knows and therefore can answer: that can be very useful for me and probably other people who may are questioning itself the same thing. The question is how to get the ID of an assistant if we create it from the Open AI website, in case that this is possible, since I am not sure about it: I try to locate the ID in the Open AI website, but, I can't locate a valid ID that then I can use with the library / API.

The idea is to use the API with an assistant which is already created using the Open AI website. Is this possible? Or may we need to create the assistant using the API in order to get the assistant ID?

Thanks very much for your help!!

**Comment by gehrisandro** [comment]
There is a page where you can find a list of all Assistants and see their IDs: https://platform.openai.com/assistants

And you can fetch a list of all assistants via API as well: https://github.com/openai-php/client#list-3

**Comment by dec** [comment]
Hello to all,

Thanks very much @gehrisandro. Yes... I forget about the ability to list the assistants... but the page that you link can be also really useful. Thanks very much again!
