### ISSUE TITLE
Obtain token consumption with the Assistants API?

### ISSUE THREAD

**Issue by absoluteweb** [openai-php/client#274]
Hi,
Is there a way to retrieve token consumption from the API when using the Assistants API?
Subsidiary question: do we know the default settings of the model we're using, since we can't enter them with the Assistants API (temperature, etc.)?
Nicolas.

**Comment by gehrisandro** [comment]
Hi @absoluteweb 

Currently there is no way (or at least I am not aware of it) to get the token usage on the Assistants API. You can see the usage in the webinterface.

The second question is out of scope of this library. Please ask this question in the community forum from OpenAI.
