### ISSUE TITLE
[Bug]: Rate Limits not being returned

### ISSUE THREAD

**Issue by s2-ieuan** [openai-php/client#288]
### Description

The response metadata rate limit info is empty, trying to access `$response->meta()->requestLimit->limit`; returns an error reading `limit` as `requestLimit` does not exist. Calling `$response->meta()->toArray()` also does not show these headers

### Steps To Reproduce

Trigger an image generation request, the rate limit stays empty

### OpenAI PHP Client Version

0.8.0

### PHP Version

8.3.0

**Comment by s2-ieuan** [comment]
It appears that this is an issue with the image generation endpoint, rather than the whole API itself. I guess there is no fix for this without OpenAI adding these headers to the relevant endpoints

**Comment by gehrisandro** [comment]
Hi @s2-ieuan 

You are right. OpenAI does not include this information in all of their responses. Therefore there is nothing we can do about it from our side.
