### ISSUE TITLE
[Bug]: when i update openai-php/client to v0.8.0, the function 'speechStream' doesn't exist。

### ISSUE THREAD

**Issue by ZhangKoven** [openai-php/client#291]
### Description

hi brother,
when i updated openai-php/client to v0.8.0, the function 'speechStream' doesn't exist。
first i run composer update openai-php/client,the function 'speechStream' doesn't exist。
and then i run composer remove openai-php/client and composer require openai-php/client
the function 'speechStream' still doesn't exist。
I don't know where went wrong，i need your help.

### Steps To Reproduce

this is my AudioContract
![微信图片_20231214083022](https://github.com/openai-php/client/assets/138736974/4a1907ab-95fc-4969-ab34-83fa9bb1b9c2)
this is github's AudioContract
![微信图片_20231214083222](https://github.com/openai-php/client/assets/138736974/5f2fe32e-380e-4988-a6a3-3be452d56cb7)

### OpenAI PHP Client Version

v0.8.0

### PHP Version

8.1.17

### Notes

thanks

**Comment by gehrisandro** [comment]
Going to create a new release today which includes the missing function.

**Comment by ZhangKoven** [comment]
ok, thank you
