### ISSUE TITLE
Make base URI configurable

### ISSUE THREAD

**Issue by LeoVie** [openai-php/client#30]
Hi,

what do you think about making the base URI configurable? At the moment, the base URI is hardcoded to `https://api.openai.com/v1`.

Making it configurable would make end-to-end testing of applications using the OpenAI client easier, as one could use an url to a mocking server in the test environment.

I would implement this as a non-breaking change via the following steps:
1. Extract interface from `OpenAI\ValueObjects\Transporter\BaseUri`
2. Change parameter type of `$baseUri` in `OpenAI\ValueObjects\Transporter\Payload::toRequest` to extracted interface
3. Add optional parameter `BaseUriInterface $baseUri = null` to `OpenAI::client`
4. Modify `OpenAI::client`, so that it handles the default value for `$baseUri` like that:
```php
public static function client(string $apiToken, string $organization = null, BaseUriInterface $baseUri = null): Client
{
    ...
    $baseUri = $baseUri ?? BaseUri::from('api.openai.com/v1');
    ...
}
```

What do you think about that? If you don't object, I would implement that.

**Comment by nunomaduro** [comment]
Just add protocol, via the `BaseUri`, if it's missing from the given string.

**Comment by LeoVie** [comment]
Okay, I will prepare a PR later that week :)

**Comment by LeoVie** [comment]
Hmm, I guess, doing it via

```php
OpenAI::client('sk-...')
    ->withBaseUri('http://api.foo-base.com/v1');
```

is not that trivial, as the `Client` created via `OpenAI::client` does not know the base URI directly, but via `HttpTransporter`. 

I've created a PR, that allows usage in the form
```php
OpenAI::clientWithBaseUri('sk-...', 'http://api.foo-base.com/v1');
```

I'm open to opinions on this :)

**Comment by gehrisandro** [comment]
This can now be achieved by using the newly introduced factory:

```php
$client = OpenAI::factory()
    ->withApiKey('<your-api-key>')
    ->withBaseUri('openai.example.com/v1')
    ->make();
```
