### ISSUE TITLE
[Bug]: transcribe 3 times and did not succeed

### ISSUE THREAD

**Issue by chengxs1994** [openai-php/client#301]
### Description

When I use larger audio files

Error: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong.

### Steps To Reproduce

        $client = OpenAI::factory()
            ->withApiKey('sk-xxx')
            ->withBaseUri('one-api.xxx.com/v1')
            ->make();

        $response = $client->audio()->transcribe([
            'model' => 'whisper-1',
            'file' => fopen(base_path().'/test.wav', 'r'),
            'response_format' => 'verbose_json',
        ]);

### OpenAI PHP Client Version

v0.7.10

### PHP Version

8.1

**Comment by chengxs1994** [comment]
The problem I encountered in SWOOLE is that I can request it normally after opening--enable-swoole-curl

**Comment by chengxs1994** [comment]
But when I use --enable-swoole-curl, the headers of the request response will become uppercase, and the logic in the code is to get lowercase, which will cause another error
![有度即时通20231222143519](https://github.com/openai-php/client/assets/129760939/790c78ce-2295-495d-8dc1-c8aa54a4e5bf)

**Comment by chengxs1994** [comment]
https://github.com/openai-php/client/pull/306

**Comment by gehrisandro** [comment]
swoole header should now work in the latest release v0.8.1
