### ISSUE TITLE
[Bug]: Delete Thread Message Endpoint is now Admin-Only (assistants/threads API)

### ISSUE THREAD

**Issue by maximehinnekens** [openai-php/client#302]
### Description

The delete thread message endpoint which was not documented yet, is now an admin-only endpoint and will result in an Exception:
```
OpenAI\Exceptions\ErrorException 

You've made a request to an admin-only URL. If you're an OpenAI employee, please request the necessary permissions. If not, it's our mistake that you're trying to access this URL -- please let us know how you found it at support@openai.com.
```

### Steps To Reproduce

Use this endpoint:
```
$response = $this->openAI->threads()->messages()->delete(
            threadId: $threadId,
            messageId: $messageId,
        );
```
        Response will result in an Exception

### OpenAI PHP Client Version

v.0.8.0

### PHP Version

8.1.2

**Comment by gehrisandro** [comment]
Hi @maximehinnekens 

Thank you very much.

Fixed here: https://github.com/openai-php/client/pull/309
