### ISSUE TITLE
Error completions createStreamed : gpt-3.5-turbo-1106

### ISSUE THREAD

**Issue by reihaniz** [openai-php/client#312]
Added
`
->withStreamHandler(fn (RequestInterface $request): ResponseInterface => $client->send($request, [
        'stream' => true
]))
`

then
`
$stream = $client->completions()->createStreamed([
    'model' => 'gpt-3.5-turbo-1106',
    'max_tokens' => 4096,
    'temperature' => 0.3,
	'messages' => [
		[
			'role' => 'user',
			'content' => "say huwa",
		],
	],
	'stream' => True,
]);
`

got an error
`Fatal error: Uncaught TypeError: {closure}(): Argument #1 ($request) must be of type RequestInterface, Nyholm\Psr7\Request given, called in \vendor\openai-php\client\src\Transporters\HttpTransporter.php on line 92`

**Comment by gehrisandro** [comment]
As the error states, you type definition is wrong:

->withStreamHandler(fn (**RequestInterface** $request): ResponseInterface => $client->send($request, [ 'stream' => true ]))

**Comment by Yalme** [comment]
> As the error states, you type definition is wrong:
> 
> ->withStreamHandler(fn (**RequestInterface** $request): ResponseInterface => $client->send($request, [ 'stream' => true ]))

Can you please explain more what your answer means? I'm getting exact same error. All code above is taken from example on project's github front page. What I need to do to solve it?
