### ISSUE TITLE
Parameters in the Fines Tunes Resource

### ISSUE THREAD

**Issue by HaneulChile** [openai-php/client#32]
Sorry for my English, but I want to know if $parameters are an array of arrays or what kind of structure I need to use because in the documentation I read that I need a JSONL so I don't know how I can make it here in PHP

`$client->fineTunes()->create($parameters);`

Thanks

**Comment by laraben** [comment]
First you need to upload your training file.
Once this is done you will have the id of the file.
Then you can create a finetuning.
This are the parameters needed (you can find more if needed in the finetune class

$parameters = [
            'model' => 'davinci',
            'training_file' => 'file-...,
        ];

**Comment by gplanchat** [comment]
Here is a complete example using a `training.jsonl` file.

```php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

const API_KEY = 'sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';

$client = OpenAI::client(API_KEY);

$file = $client->files()->upload([
    'purpose' => 'fine-tune',
    'file' => fopen(__DIR__.'/training.jsonl', 'r'),
]);

$result = $client->fineTunes()->create([
    'training_file' => $file->id,
]);
```

**Comment by gehrisandro** [comment]
Our README is a bit weak there. I am going to improve the file tunes section.
