### ISSUE TITLE
[Bug]: Call to undefined method OpenAI\Client::factory() in Laravel

### ISSUE THREAD

**Issue by agiche** [openai-php/client#329]
### Description

Hi team, 

We get the following error when trying to set different client.
`Call to undefined method OpenAI\Client::factory()`

Composer info:` "openai-php/laravel": "^0.6.0",`

### Steps To Reproduce

Install "`openai-php/laravel`" over composer.

`use OpenAI\Laravel\Facades\OpenAI;`
Try to set a client using the example code provided in the docs.

### OpenAI PHP Client Version

"openai-php/laravel": "^0.6.0",

### PHP Version

8.1.18

**Comment by gehrisandro** [comment]
Hi @agiche

Please make sure you are using the latest version (v0.8.x) and you don't have to you the factory. You can use the endpoint directly on the facade. See https://github.com/openai-php/laravel?tab=readme-ov-file#get-started

If this does not help, feel free to reopen the issue.
