### ISSUE TITLE
Thoughts on using illuminate/collections to avoid direct array access wherever possible?

### ISSUE THREAD

**Issue by shahlin** [openai-php/client#35]
Currently, as per the README example, I would have to access a `completion` this way:
```php
echo $result['choices'][0]['text'];

OR

echo $result->choices[0]->text;
```

Proposal using [illuminate/collections](https://github.com/illuminate/collections):
```php
echo $result->choices->first()->text;
```

In my opinion, it doesn't have any major impact but still cuts down the direct array access

**Comment by nunomaduro** [comment]
No plans for that at this time.
