### ISSUE TITLE
[Enhancement] streaming support for assistant api 

### ISSUE THREAD

**Issue by mgalinskiSaticon** [openai-php/client#357]
As opposed in the following Q&A, OpenAI has published the support for Message Streaming for the Assistant API, which has been documented. As such I want to open an issue for it.

Q&A Message:
_Originally posted by @eng-ahmad-sameer in https://github.com/openai-php/client/discussions/351_

OpenAI Assistant Streaming Documentation
https://platform.openai.com/docs/api-reference/assistants-streaming

**Comment by slaven-ii** [comment]
I was thinking of opening the same thing and was looking at the other completion stream implementations to try and implement myself but didn't make much progress. Would love this feature to be added

**Comment by olPdy** [comment]
Need this feature for my project too. I'm looking forward to it

**Comment by gerdemann** [comment]
Is anyone already working on the feature? Is there anything I can do to help?

**Comment by CaptainHilly** [comment]
+1 for streaming assistant support pretty, pretty please.

**Comment by sarathisahoo-muffins** [comment]
Any updates on it. We are blocked due to not having this feature.

Thanks,
Sarathi

**Comment by gehrisandro** [comment]
Implemented in the latest release: https://github.com/openai-php/client/releases/tag/v0.9.0
