### ISSUE TITLE
[Bug]: Images (Dall-e 3) method not working with Azure

### ISSUE THREAD

**Issue by kukicado** [openai-php/client#358]
### Description

Trying to create a custom factory to use Dall-e 3 with Azure does not work with the client library.  It gives a "resource not found" error, although the resource exists and works with other client libraries.

<img width="563" alt="Screenshot 2024-03-19 at 1 53 42 PM" src="https://github.com/openai-php/client/assets/1770570/5393e51e-eae8-40c8-b2af-df182f386f69">

### Steps To Reproduce

1) Setup an Azure OpenAI factory:

$client = \OpenAI::factory()
        ->withBaseUri('{resource}.openai.azure.com/openai/deployments/{deployment-name}')
        ->withHttpHeader('api-key', 'XXXXX')
        ->withQueryParam('api-version', '2023-06-01-preview')
        ->make();

    $response = $client->images()->create([
        'prompt' => 'a monkey eating a banana',
        'n' => 1,
        'size' => '1024x1024',
        //'response_format' => 'url',
    ]);

2) Try to run the route, get "resource not found" exception.

I have tried changing the base URI to `{resource}.openai.azure.com` as well and added deployment name in the create method, but the issue persists.

### OpenAI PHP Client Version

^0.8.4

### PHP Version

8.2.12

**Comment by berott** [comment]
API-Version `2024-02-15-preview` has helped for me!

**Comment by gehrisandro** [comment]
Hi @kukicado  

This does not look like an error related to the package.

If you do not agree, feel free to reopen the issue.
