### ISSUE TITLE
all results truncated

### ISSUE THREAD

**Issue by wyatt121** [openai-php/client#37]
Hi,

All my results to prompts are getting truncated.  Typically less than a sentence is returned.  Any idea why?  Example below:

Any help is much appreciated.

Wyatt

My prompt: 

 "Write me a story."

Result:  

  [model] => text-davinci-003
    [choices] => Array
        (
            [0] => OpenAI\Responses\Completions\CreateResponseChoice Object
                (
                    [text] => 

Once upon a time, there was a young girl named Daisy who was
                    [index] => 0
                    [logprobs] => 
                    [finishReason] => length
                )

        )

    [usage] => OpenAI\Responses\Completions\CreateResponseUsage Object
        (
            [promptTokens] => 4
            [completionTokens] => 16
            [totalTokens] => 20
        )

)

**Comment by gehrisandro** [comment]
You haven't provided your request but it looks like you have set the token limit (max_tokens) to 20.

Increase this value to get a longer response.
