### ISSUE TITLE
[Improvement]: `dd` is not a PHP function, the first image of readme.md needs to be changed. use `var_dump` or `print_r`

### ISSUE THREAD

**Issue by simaranjit** [openai-php/client#372]
### Description

`dd` is not a standard PHP function, probably it comes from Laravel framework, however this is a standard core PHP client, so I would strongly recommend to change`dd` to `var_dump` or `print_r` in the first image added in readme.md

### Steps To Reproduce

If you preview the readme.md, the first image shown needs to be fixed 

### OpenAI PHP Client Version

main branch

### PHP Version

8.1

### Notes

`dd` is not a standard PHP function, probably it comes from Laravel framework, however this is a standard core PHP client, so I would strongly recommend to change`dd` to `var_dump` or `print_r` in the first image added in readme.md

**Comment by nunomaduro** [comment]
No plans to change that.
