### ISSUE TITLE
Fatal error: Cannot declare class OpenAI, because the name is already in use in E:\Xampp_8.2\htdocs\ia\vendor\openai-php\client\src\OpenAI.php on line 8 [Bug]: 

### ISSUE THREAD

**Issue by neutronixx** [openai-php/client#378]
### Description

Installing and testing the repo I get this error: Fatal error: Cannot declare class OpenAI, because the name is already in use in E:\Xampp_8.2\htdocs\ia\vendor\openai-php\client\src\OpenAI.php on line 8

### Steps To Reproduce

using the example code on home page i get this error

### OpenAI PHP Client Version

v0.8.5

### PHP Version

8.2

**Comment by NilsCJ** [comment]
I have the same issue, and I couldn't find the answer yet.

**Comment by graphem** [comment]
My issue was that I used use OpenAI\OpenAI;

Fixed with use OpenAI;
