### ISSUE TITLE
[Feature]: Compatibility with assistants v2

### ISSUE THREAD

**Issue by gerdemann** [openai-php/client#379]
Hallo zusammen,

arbeitet gerade schon jemand an der v2 der Assistants API? Wenn ja, kann ich da irgendwie unterstützen?

Hier die migrationsdokumentation:
https://platform.openai.com/docs/assistants/migration

**Comment by yvescleuder** [comment]
Upp!!

**Comment by mo7amedmamdouh** [comment]
Up

**Comment by gerdemann** [comment]
See #381
