### ISSUE TITLE
Undefined array key "events"

### ISSUE THREAD

**Issue by asivaneswaran** [openai-php/client#38]
I get the following error: `Undefined array key "events"`

Here is the stack trace:
```   ErrorException

  Undefined array key "events"

  at vendor/openai-php/client/src/Responses/FineTunes/RetrieveResponse.php:52
     48▕     public static function from(array $attributes): self
     49▕     {
     50▕         $events = array_map(fn (array $result): RetrieveResponseEvent => RetrieveResponseEvent::from(
     51▕             $result
  ➜  52▕         ), $attributes['events']);
     53▕
     54▕         $resultFiles = array_map(fn (array $result): RetrieveResponseFile => RetrieveResponseFile::from(
     55▕             $result
     56▕         ), $attributes['result_files']);
```

Here is the code I am running: `$response = $client->fineTunes()->list();`

**Comment by nunomaduro** [comment]
@asivaneswaran Can you try to make a pull request that addresses the issue? Also, probably try to understand why `event` were there in the same place.

**Comment by paulber33** [comment]
I can create a PR to fix this. 
Idea:
Create a RetrieveResponseList class that doesn't use events. And then use that instead of RetrieveResponse in the ListResponse class.

@nunomaduro Does that make sense or did you have something else in mind?
