### ISSUE TITLE
[file_search]: Do we have to wait for the v2 API to get file_search?

### ISSUE THREAD

**Issue by Damien514** [openai-php/client#388]
### Description

When I test my assistant in the Playground, it gets my data from my files Vector Stores and can answer all of my questions related to people in my organization. When I ask the same question using my PHP script, it always says it has no info on this person. Does it means that "file_search" is not possible for the moment with the v1 API ?

I know, that's not a bug, more a question, sorry for that!

### Steps To Reproduce

In my PHP:

1. Create a thread
`$response = $client->threads()->create([]);`
2. Create a message
```
$response = $client->threads()->messages()->create($threadId,
	[
		'role' => 'user',
		'content' => $obj
	]
);
```
3. Run
```
$response = $client->threads()->runs()->create(
	threadId: $threadId,
	parameters: [
		'assistant_id' => 'asst_xxxxxxxxxx',
	],
);
```
3. Retrieve my run
```
$response = $client->threads()->runs()->retrieve(
		threadId: $threadId,
		runId: $runId,
	);
```
4. get the answer
`$response = $client->threads()->messages()->list($threadId, ['limit' => 1,]);`

### OpenAI PHP Client Version

v.0.8.5

### PHP Version

8.1

### Notes

Thanks!

**Comment by GrayHoax** [comment]
Did you try to create assistant with `tools` with `'type' => 'file_search'`?
I think vector store id defining in this method - https://platform.openai.com/docs/api-reference/assistants/createAssistant
only fyi - https://platform.openai.com/docs/api-reference/vector-stores/object

**Comment by knash94** [comment]
Hey @Damien514 ,

Since this SDK is only using V1 of the assistants API at the moment then you may need to attach the file to the assistant using the API rather than the OpenAI interface. Have you tried something along these lines?

```php
$client->assistants()->modify('asst_xxxxxxxxxx', [
    'file_ids' => ['file-xxx']
]);
```

**Comment by stephenr85** [comment]
Also interested. I am attaching files to the assistant for the time being, but the SDK throws an error trying to use "file_search" as a tool value in all contexts I've tried.

**Comment by rkuhl** [comment]
It seems to me that this is just a naming issue; `file_search` was previously named `retrieval`. 
Try `retrieval` when using v1 API
