### ISSUE TITLE
Undefined array key "file_ids"[Bug]: 

### ISSUE THREAD

**Issue by nedikexpando** [openai-php/client#389]
### Description

By calling threads->createAndRun() it throws an exception 'Undefined array key "file_ids"'
The same is when calling threads()->messages()->list()

### Steps To Reproduce

```
try {
                $response = $this->client->threads()->createAndRun(
                    [
                        'assistant_id' => $this->getOpenAiAssistantId(),
                        'thread' => [
                            'messages' => [['role' => 'user', 'content' => $userText,],],
                        ],
                    ],
                );
             
                return $response->threadId;
            } catch (Exception $e) {
               dump($e);
            }
```

### OpenAI PHP Client Version

v0.8.5

### PHP Version

8.3

**Comment by LMCom** [comment]
I assume you are using GPT-4o which also requires an assistant v2. That's a very recent change to which this repository is not yet adjusted.
Try an earlier GPT version with an assistant v1. It should work.

**Comment by prashantadevkota-bg** [comment]
If you want to see how the V2 API behaves, then you can use the below quick hack to support creating assistants, threads & messages. It also will allow you to read back the responses from the AI. It will even support using the latest Model, which is 4_O.

All you need to do is apply the change in three files like shown in the image below. Please note that this is a hack-y solution if you are too impatient.

![bug-fix-for-v2](https://github.com/openai-php/client/assets/141619606/7a14871b-1a1a-4117-93e5-b49b73fdcd3d)

**Comment by udgithub** [comment]
can you estimate when you will have adapted this cool PHP library to Open AI assistants API v2?

**Comment by gehrisandro** [comment]
I am currently working on the v2 implementation, but it is a lot to do.

Feel free to give it an extra boost [github.com/sponsors/gehrisandro](https://github.com/sponsors/gehrisandro) 😅
