### ISSUE TITLE
Add Timeout Param

### ISSUE THREAD

**Issue by Justintime50** [openai-php/client#39]
The official Python library allows a timeout to be set on requests. It would be really helpful for production applications to be able to set up a timeout on requests so we don't keep our web workers hanging if there is hiccups in connections or issues on the OpenAI side.

**Comment by nunomaduro** [comment]
Can you make a pull request adding that feature?

**Comment by Justintime50** [comment]
Hmmm, it doesn't even look like the [PSR7 lib](https://github.com/guzzle/psr7) that is used here to make HTTP calls supports timeouts at all if I'm looking through their code correctly? Would potentially require a wrapper around the requests to handle this since it's not supported native.

**Comment by gehrisandro** [comment]
This can now be achieved by using the newly introduced factory:

```php
$client = OpenAI::factory()
    ->withHttpClient(new \GuzzleHttp\Client(['timeout'  => 2.0]))
    ->make();
```
