### ISSUE TITLE
API V2 Library?

### ISSUE THREAD

**Issue by nibblebits** [openai-php/client#390]
I have a ChatGPT assistant pacakge I released here: https://packagist.org/packages/dragonzap/openai-chatgpt-assistant we depend directly on your package, we want to support the V2 api do you know when or if you plan to upgrade your package to support V2 api, please let me know so I can decide wether or not to fork your repository 

Thank you!
Dan

**Comment by PatricioCabo** [comment]
hey @nibblebits, check [this](https://github.com/openai-php/client/issues/381) out.. it worked for me, hope it helps you as well 👍

**Comment by nibblebits** [comment]
@PatricioCabo Thanks I found the comment you are talking about
