### ISSUE TITLE
Support Stream for Thread using Assistant

### ISSUE THREAD

**Issue by sarathisahoo-muffins** [openai-php/client#391]
Hi,
The Stream feature is not there to use Assistant using Thread. This is very important feature to have.

**Comment by GrayHoax** [comment]
Hi, @sarathisahoo-muffins 
I think, that defining stream handler may helps to catch response from stream:
```
    ->withStreamHandler(fn (RequestInterface $request): ResponseInterface => $client->send($request, [
        'stream' => true // Allows to provide a custom stream handler for the http client.
    ]))
```
Can you test this hypothesis?

**Comment by knash94** [comment]
There is an open PR #367, hopefully this will be reviewed and merged in soon without any big changes to the interface. The issue has also already been raised on #357

**Comment by Muhammad-Huzaifa7** [comment]
yeh please update it because like me many programmer want to use streaming assistant response by this library

**Comment by iamaz007** [comment]
check this out
[https://github.com/openai-php/client?tab=readme-ov-file#create-streamed-2](url)

**Comment by gehrisandro** [comment]
Implemented in the latest release: https://github.com/openai-php/client/releases/tag/v0.9.0
