### ISSUE TITLE
An issue on Fine Tune List API: when the status_details of a RetrieveResponseFile is an exception message (string)

### ISSUE THREAD

**Issue by rodrigoisabelo** [openai-php/client#45]
Hi, I encountered an issue with retrieving the list of fine tunes. 
1. I uploaded a JSONL file
2. Used the file to create a new fine-tune
3. When I tried to retrieve the list of fine tunes.
4. It gave me this error.

I suspect this is because the status details show that the file I uploaded was invalid. However, this is not really an issue with the package. But it would be great if the package could also handle this scenario.

I hope this can be resolved soon. Thanks!

OpenAI\Responses\FineTunes\RetrieveResponseFile::__construct(): Argument #8 ($statusDetails) must be of type ?array, string given, called in /var/www/html/vendor/openai-php/client/src/Responses/FineTunes/RetrieveResponseFile.php on line 50

The exception upon checking:
![image](https://user-images.githubusercontent.com/100250620/219321917-fcbc8f4d-93ee-4aaf-aae4-8e8e5e03aa42.png)

The stack trace I received:
![image](https://user-images.githubusercontent.com/100250620/219321988-80218930-59b2-4de7-8277-74acda0b9de2.png)

**Comment by nunomaduro** [comment]
Can you make a pull request?

**Comment by shutupflanders** [comment]
This is still an issue, can it be reopened?

`OpenAI\Responses\FineTunes\RetrieveResponseFile::__construct(): Argument #8 ($statusDetails) must be of type ?array, string given, called in /app/vendor/openai-php/client/src/Responses/FineTunes/RetrieveResponseFile.php on line 50`

**Comment by rodrigoisabelo** [comment]
Hi @shutupflanders, it's good to know there are others who have experienced this issue, can you provide us again the step-by-step guide on how to replicate it?  Wasn't able to give @gehrisandro since I already refactored my code. So that he can help us and prevent this to happen to other developers as well. Thanks!

Will re-open this issue.

**Comment by shutupflanders** [comment]
I uploaded a massive JSONL document with parsing errors in it (unescaped quote) by mistake, saw the error above, and got the following when hitting the `/v1/fine-tunes` endpoint manually:

`"status_details": "Invalid file format. Example 1196 cannot be parsed. Error: line contains invalid json: Expecting ',' delimiter: line 1 column 65 (char 64) (line 1196)"`

**Comment by rodrigoisabelo** [comment]
> I uploaded a massive JSONL document with parsing errors in it (unescaped quote) by mistake, saw the error above, and got the following when hitting the `/v1/fine-tunes` endpoint manually:
> 
> `"status_details": "Invalid file format. Example 1196 cannot be parsed. Error: line contains invalid json: Expecting ',' delimiter: line 1 column 65 (char 64) (line 1196)"`

And this means the `status_details` wasn't an array right? It's an exception message `string` came from the OpenAI API endpoint. _(This is a confirmation so we can decide what to do next)_

**Comment by shutupflanders** [comment]
Correct, and when there's no error - it returns `null`, not an array:

```
  "status": "processed",
  "status_details": null
```

**Comment by gehrisandro** [comment]
Thanks @shutupflanders 

Your hint to upload a large file enabled me to reproduce the issue. (errors in smaller files already get detected while uploading)

Still not sure if `status_details` can be an object too, but we will see: https://github.com/openai/openai-openapi/issues/24 👀
