### ISSUE TITLE
[Bug]: Repo files not matching zip or what is in composer

### ISSUE THREAD

**Issue by ericthornton88** [openai-php/client#461]
### Description

I have been trying to utilize `project` in the factory class so I can access different assistants. However, the code in the Github repo does not match the zip code or the code that downloads with composer require.

### Steps To Reproduce

- Go to https://github.com/openai-php/client/blob/main/src/Factory.php and you will see a property and method related to projects (line 34 and 85 are two examples)
- Go to https://github.com/openai-php/client/releases/tag/v0.10.1 and download the ZIP file. Open the src/Factory.php and verify there is nothing with the project functionality.

### OpenAI PHP Client Version

v0.10.1

### PHP Version

8.2

**Comment by iBotPeaches** [comment]
If you look at your first link you are looking at branch main, your 2nd link is download of tag v0.10.1. When I look at the v0.10.1 source for your zip - I don't see any project property.

https://github.com/openai-php/client/blob/v0.10.1/src/Factory.php

You seem to be comparing two different points in history so they won't line up.
