### ISSUE TITLE
[Bug]: Argument #1 ($attributes) must be of type array, string given

### ISSUE THREAD

**Issue by bytestream** [openai-php/client#478]
### Description

```
OpenAI\Responses\Models\ListResponse::from(): Argument #1 ($attributes) must be of type array, string given, called in /vendor/openai-php/client/src/Resources/Models.php on line 30
```

https://github.com/openai-php/client/blob/061a73827795d01a4fab1a580e08bc5b92d90999/src/Resources/Models.php#L30 [`$response->data()`](https://github.com/openai-php/client/blob/061a73827795d01a4fab1a580e08bc5b92d90999/src/ValueObjects/Transporter/Response.php#L48) returns `array|string` but `ListResponse::from()` only accepts `array`.

`$response->data()` is **intermittently** returning `"404 page not found\n"`

### Steps To Reproduce

```php
OpenAI::client('...')->models()->list()->data
```

### OpenAI PHP Client Version

v0.10.1

### PHP Version

8.1.24

**Comment by gehrisandro** [comment]
Hi @bytestream 

I am not able to reproduce the bug. Feel free to reopen the issue, if you can still reproduce the error.

**Comment by applibs** [comment]
Today I have same error.
OpenAI\Responses\Chat\CreateResponse::from(): Argument #1 ($attributes) must be of type array, string given

**Comment by bytestream** [comment]
I can still replicate, but as I mentioned it’s intermittent and due to some issue on OpenAIs API. The PHP doc shows that string is a possible return type but it only handles the array case. Type handling needs to be improved. 

For some reason it won’t let me reopen the issue @gehrisandro

**Comment by bessone** [comment]
I had this error for the first time yesterday, one among a few hundred calls

**Comment by adeng-kirbydrive** [comment]
Hey, receiving the same issue. It's pretty rare, 1 in a few hundred, like bessone said.

**Comment by xbojer** [comment]
I have seen this too but with 50x response from OpenAI. Don't want to duplicate issue, but I also don't have permissions to reopen this one...

**Comment by yhael-aloware** [comment]
A few months with this issue for different models, particularly Threads, Runs and Messages

**Comment by dvolkering** [comment]
I have this issue regularly, running this command every 10-20 seconds and happens multiple times a day. There is no particular reason in my input which can cause this issue.

**Comment by jordanade** [comment]
Just got this for the first time (in more than a year of use), out of the blue.

**Comment by krabatak1** [comment]
pareil nous avons ce cas depuis environ 2 mois au téléphone : c'est pas énorme mais quelques cas similaires.

**Comment by iBotPeaches** [comment]
I released v0.16.0 this morning. It should prevent this from happening - you'll get an actual ErrorException or RateLimitException now instead of an unhandled crash.

**Comment by bkremenovic** [comment]
I’m seeing the same exception right now. Does anyone know what might be causing it or how to fix it?

**Comment by iBotPeaches** [comment]
This issue was reported on version v0.10.x - since then on present v0.16.1 a good chunk of entire exception reporting has been replaced. The root cause is available in detail in this PR: https://github.com/openai-php/client/pull/643

Upgrading to latest will fix it. If it doesn't - I need a full stack-trace, because it will not be exactly the same issue as this thread

**Comment by bkremenovic** [comment]
Thanks @iBotPeaches!

Seems like an upgrade to the very latest version fixes this
