### ISSUE TITLE
[Bug]: Fail gracefully on unsuccessful request

### ISSUE THREAD

**Issue by NoxArt** [openai-php/client#479]
### Description

If the request fails, [this line](https://github.com/openai-php/client/blob/main/src/Transporters/HttpTransporter.php#L51) will simply crash on "Call to a member function getBody() on null" instead of handling this usecase somehow - at least to convert it to a semantic exception e.g. RequestFailedException or something

Thank you

### Steps To Reproduce

Make a request that will somehow fail, maybe towards non-existing endpoint?

For us it fails during Files->Download

It _may_ be related to response "The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.co..."

### OpenAI PHP Client Version

v0.10.1

### PHP Version

8.1.27

**Comment by NoxArt** [comment]
Btw there are similar failures:

OpenAI\Responses\Batches\BatchResponse::__construct(): Argument #1 ($id) must be of type string, null given

OpenAI\ValueObjects\Transporter\Response::from(): Argument #1 ($data) must be of type array|string, null given

...

The library generates many generic errors that is not easy to handle nicely

**Comment by gehrisandro** [comment]
Hi @NoxArt 

Feel free to submit a PR to improve the error handling.
