### ISSUE TITLE
[Bug]: Cannot upload file from php://temp stream

### ISSUE THREAD

**Issue by supriyo-biswas** [openai-php/client#498]
### Description

I'm unable to use streams based on `php://temp` to upload files, which results in an `OpenAI\Exceptions\ErrorException` being thrown with the message `The browser (or proxy) sent a request that this server could not understand`.

However, I am able to use regular files in the upload files API.

For my use case, I'd like to avoid writing an on-disk file, and therefore would like to have the ability to upload a `php://temp` file.

### Steps To Reproduce

Running the following code will help reproduce the error:

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

$client = OpenAI::client(getenv('OPENAI_API_KEY'));

$data = <<<'EOM'
{"custom_id": "request-1", "method": "POST", "url": "/v1/chat/completions", "body": {"model": "gpt-4o-mini", "messages": [{"role": "system", "content": "You are a helpful assistant."},{"role": "user", "content": "Hello world!"}],"max_tokens": 1000}}

EOM;

$stream = fopen('php://temp', 'r+');
fwrite($stream, $data);
rewind($stream);

$fileResponse = $client->files()->upload(
    parameters: [
        'purpose' => 'batch',
        'file' => $stream,
    ]
);

$fileId = $fileResponse->id;
dump($fileId);
```

Changing the above code to the following, and saving the content of the file in a `batch.json` file resolves the issue:

```
<?php
// ...
$stream = fopen('batch.jsonl', 'r+');

$fileResponse = $client->files()->upload(
    parameters: [
        'purpose' => 'batch',
        'file' => $stream,
    ]
);
// ...
```

### OpenAI PHP Client Version

v0.10.2

### PHP Version

8.3.6

**Comment by gehrisandro** [comment]
Hi @supriyo-biswas 

Not sure if this is something we can fix on our side.

If you find a solution, feel free to submit a PR.

**Comment by supriyo-biswas** [comment]
I guess if you wanna paste AI slop without understanding what they were trying to say, it’s your call. I’m out.

(Just to help you out: we’re talking about fixing the internal implementation to support streams, not what about you can do from outside the library.)

**Comment by rahmani-djamel** [comment]
@supriyo-biswas 
You’re right  but I’d like to share a suggestion for anyone facing streaming issues with S3 buckets and OpenAI. I know this is an internal package issue, but I’m posting the solution to help others who **encounter the same problem.**


Deleted
