### ISSUE TITLE
Request with context

### ISSUE THREAD

**Issue by androidformax** [openai-php/client#53]
I could not make a request with the context that preceded the conversation. Is this functionality not implemented, or am I looking at the wrong function? Maybe you don't call it context, but something else?

**Comment by doc-** [comment]
You need to store the messages in a database and prompt them in the request as you loop for them.
For example, the initial prompt is your global context is:
"You are a chatbot, you answser the user about the software features. The software costs $499/month [detail all your other features]"

Your create a chat interface with an input.

You type:
"How much the software cost?" -> save this message in db

Send to the prompt the initial context + your question.

IA responds:
"The software costs $499/month." -> save also this message.

Ask a new question: the prompt now contains initial context + your question + AI answer.

And so on.

When you send your context for each message in your thread, you have to prompt your initial context plus the subsequent messages.

**Comment by gehrisandro** [comment]
@androidformax Your question does not look like a library related issue. Is it fine for you when I close the issue?

**Comment by androidformax** [comment]
> When you send your context for each message in your thread, you have to prompt your initial context plus the subsequent messages.

Do I just need to add data from the database to promt? Or is there a separate parameter like Context for that?

**Comment by gehrisandro** [comment]
@androidformax There is no separate parameter. You have to provide everything within the `prompt`.

For more information see the official documentation on how to create prompts: https://platform.openai.com/docs/guides/completion/introduction
