### ISSUE TITLE
($finishReason) must be of type string

### ISSUE THREAD

**Issue by diudiudiuu** [openai-php/client#54]
local.ERROR: OpenAI\Responses\Completions\CreateResponseChoice::__construct(): Argument #4 ($finishReason) must be of type string, null given, called in /data1/chatgpt/vendor/openai-php/client/src/Responses/Completions/CreateResponseChoice.php on line 22 {"exception":"[object] (TypeError(code: 0): OpenAI\\Responses\\Completions\\CreateResponseChoice::__construct(): Argument #4 ($finishReason) must be of type string, null given, called in /data1/chatgpt/vendor/openai-php/client/src/Responses/Completions/CreateResponseChoice.php on line 22 at /data1/chatgpt/vendor/openai-php/client/src/Responses/Completions/CreateResponseChoice.php:9)
[stacktrace]

**Comment by anandmainali** [comment]
yeah i'm having the same issue multiple times.

**Comment by careybaird** [comment]
Duplicate of #50  (see this issue for a fix)

**Comment by diudiudiuu** [comment]
> Duplicate of #50 (see this issue for a fix)

thank you

**Comment by nunomaduro** [comment]
Fixed on `v0.3.2`.
