### ISSUE TITLE
new chat completion endpoint (api version 1.2.0)

### ISSUE THREAD

**Issue by clarkrickman2** [openai-php/client#58]
Does this support ChatCompletion?

import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)

**Comment by clarkrickman2** [comment]
import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)

**Comment by rverrips** [comment]
Dear  @clarkrickman2 
I believe the "gpt-3.5-turbo" model was only made available today, March 1st
Perhaps wait for the next release - I'd also suggest to relabel your issue to "gpt-3.5-turbo" (not ChatGPT) to avoid confusions.  
ChatGPT is the frontend hosted by OpenAI, not the API which this package provisions.  
ChatGPT does use the gpt-3.5-turbo API internally - hence the need for clarification.

**Comment by nunomaduro** [comment]
cc @gehrisandro

**Comment by gehrisandro** [comment]
Hi @clarkrickman2 

Currently it does not support the Chat endpoint as it is only available for a around one hour now. While introducing the new endpoint (see their [news](https://openai.com/blog/introducing-chatgpt-and-whisper-apis)) they have updated their API specs to version 1.2.0: https://github.com/openai/openai-openapi/pull/19/files

This makes another features available (audio transcription) and has some other minor changes. I will create dedicated issues for the various changes made in version 1.2.0 so we can tackle them one by one.

**Comment by gehrisandro** [comment]
@clarkrickman2 

Implementation done: https://github.com/openai-php/client/pull/60

You might have a look and give me some feedback, if you think I missed something.

**Comment by rodrigoisabelo** [comment]
I'm excited for this PR to get published, looking forward to this

**Comment by rodrigoisabelo** [comment]
Can't wait for this PR to get merged and published to Packagist. Looking forward to it guys.

**Comment by benbjurstrom** [comment]
> @clarkrickman2
> 
> Implementation done: #60
> 
> You might have a look and give me some feedback, if you think I missed something.

Wasn't expecting this to get implemented so quickly. Amazing work!

**Comment by nunomaduro** [comment]
Done: Done: https://twitter.com/enunomaduro/status/1631221339028684802?s=20.
