### ISSUE TITLE
add new audio transcription and translation endpoints (API version 1.2.0)

### ISSUE THREAD

**Issue by gehrisandro** [openai-php/client#59]
https://platform.openai.com/docs/api-reference/audio

**Comment by gehrisandro** [comment]
This seems to be fun 🙈 

The request has a parameter `response_format` which can be set to one of the following: json, text, srt, verbose_json, or vtt.

As the parameter name suggests, this results in very different return messages. Here are example messages of the various formats:

**text**
`Hello, how are you? Fine and you? What is your name? My name is Tom.\n`

**json**
`{"text":"Hello, how are you? Fine and you? What is your name? My name is Tom."}`

**verbose_json**
```json
{
  "task": "transcribe",
  "language": "english",
  "duration": 11.83,
  "segments": [
    {
      "id": 0,
      "seek": 0,
      "start": 0.0,
      "end": 12.32,
      "text": " Hello, how are you? Fine and you? What is your name? My name is Tom.",
      "tokens": [
        50364,
        ...,
        50980
      ],
      "temperature": 0.0,
      "avg_logprob": -0.3095785223919412,
      "compression_ratio": 1.0625,
      "no_speech_prob": 0.031427089124917984,
      "transient": false
    }
  ],
  "text": "Hello, how are you? Fine and you? What is your name? My name is Tom."
}
```

**vtt**
```
WEBVTT\n
\n
00:00:00.000 --> 00:00:12.320\n
Hello, how are you? Fine and you? What is your name? My name is Tom.\n
\n
```

**srt**
```
1\n
00:00:00,000 --> 00:00:12,320\n
Hello, how are you? Fine and you? What is your name? My name is Tom.\n
\n
\n
```

I am not an audio expert but I guess there is a good reason to have different out formats. But in a REST way this is quiet weird, as it breaks with every REST standard.

Right now I am not sure how to handle this properly. Currently I have the following ideas:

1) Always force `verbose_json` and return a corresponding response which has more or less the same format as all the other responses.

2) Let the API user control the `response_format` parameter and return a response corresponding to the format the user has chosen. `text`=> `TranscriptionTextResponse`; `vtt`=> `TranscriptionVttResponse` etc.

3) Always force `verbose_json` in the background (similar to idea 1) but provide on the response object methods for all the available formats (ex. `$response->json()` or `$response->vtt()`) which will return the response in the correct format. This would probably be the most convenient option for the package users, but we have to rebuild the format conversion in our package and can not make use of the API functionality which is some kind of an overhead and maybe lead to more errors.

@nunomaduro What do you think which option to prefer? Or do you have another idea?

Spontaneously I would go for option 2 even if it's a bit weird to have multiple possible response classes.

**Comment by NumairAwan** [comment]
@gehrisandro any ETA when it will done?

**Comment by nunomaduro** [comment]
@NumairAwan No ETA. Keep in mind, we work on this in our free time.

**Comment by mpociot** [comment]
IMHO 2 seems the way to go. I can see a lot of valid reasons to use the other response formats, so enforcing JSON doesn't seem good to me.

**Comment by gehrisandro** [comment]
While implementing I took a little different approach:

`$client->audio()->transcribe([...])` will always return a `TranscriptionResponse` regardless which `response_format` was chosen.

The returned value from the API is then always stored within the `text` property. All the other properties `task`, `language`, etc. are only filled if `response_type = verbose_json`. Otherwise they are all null.

@mpociot @nunomaduro What do you think?

**Comment by gehrisandro** [comment]
By the way `translate()` is an exact copy of `transcribe()` because both endpoints currently behave in the exact same way but I guess sooner or later these two endpoints will divert and therefore I created two different response classes even if it is not necessary right now.

**Comment by NumairAwan** [comment]
@gehrisandro i was also implementing audio endpoint but faced the same issue, i was needed to integrate whisper in project but i guess i need to wait for the implementation.

**Comment by gehrisandro** [comment]
released: https://twitter.com/gehrisandro/status/1631554420558233601
