### ISSUE TITLE
add chatgpt3.5

### ISSUE THREAD

**Issue by diudiudiuu** [openai-php/client#61]
doc uri https://platform.openai.com/docs/api-reference/chat

**Comment by diudiudiuu** [comment]
[Composer](https://getcomposer.org/)
thank you

**Comment by diudiudiuu** [comment]
![image](https://user-images.githubusercontent.com/31238774/222337994-78375f7e-df19-4624-974b-66aafdfa839a.png)
composer install openai, but not find chat.

**Comment by nmeirik** [comment]
When I attempt to use the `gpt-3.5-turbo` model, I get the following response from the API:

> This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

**Comment by rodrigoisabelo** [comment]
Hi @nmeirik 

OpenAI Chat API is different from Completions API. If you want to use `gpt-3.5-turbo`, this package does not support it yet, but the PR is on the way #60 . You can use `text-davinci-003` for now on Completions API.

**Comment by dilab** [comment]
can't wait to have this PR merged!

**Comment by diudiudiuu** [comment]
> When I attempt to use the `gpt-3.5-turbo` model, I get the following response from the API:
> 
> > This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

yeah, But it not v1/chat/completions

**Comment by diudiudiuu** [comment]
> Hi @nmeirik
> 
> OpenAI Chat API is different from Completions API. If you want to use `gpt-3.5-turbo`, this package does not support it yet, but the PR is on the way #60 . You can use `text-davinci-003` or other text-based models for now on Completions API.

I can not wait any more

**Comment by nunomaduro** [comment]
Done: https://twitter.com/enunomaduro/status/1631221339028684802?s=20.
