### ISSUE TITLE
Symfony Bundle

### ISSUE THREAD

**Issue by GromNaN** [openai-php/client#64]
Hi, thank you for this library that is very easy to use.

I created a Symfony bundle by copying things from the Laravel integration. You can find it here: https://github.com/GromNaN/openai-symfony (work in progress).

What do you think of moving this project into the `openai-php` organisation? It would be good for this project to provide an integration with a 2nd major framework. The bundle is not published on Packagist yet, so that it would be a clean start.

**Comment by nunomaduro** [comment]
Excellent idea. Just created the repository, and added you as maintainer. Can you make sure the project, structure, coding style, readme, (everything really), looks exactly like the client / laravel integration? Thanks! 

- https://github.com/openai-php/symfony.
- https://github.com/openai-php/symfony/invitations.

**Comment by GromNaN** [comment]
Excellent. I'm going to do this right.

**Comment by nunomaduro** [comment]
Let me know when is ready, and i will review it. ✔️

**Comment by GromNaN** [comment]
Ready. You can submit on Packagist whenever you want to.

There is a [phpstan error](https://github.com/openai-php/symfony/actions/runs/4327840200) that I'll dig with the Symfony team.

**Comment by nunomaduro** [comment]
Done. So, now I guess we have the HTTP client issue + the tests not passing issue, that's correct?

**Comment by GromNaN** [comment]
Thank you for the publication on [packagist](https://packagist.org/packages/openai-php/symfony).
Tests are green after https://github.com/openai-php/symfony/commit/c7d4a74322f7afd8f83f708ef99bf9b8bb579be0 (and the bundle is working again).

**Comment by GromNaN** [comment]
Closing as the bundle have been tagged. Thanks.
