### ISSUE TITLE
Add Proxy Support for HTTP Request

### ISSUE THREAD

**Issue by geekr-dev** [openai-php/client#67]
Can you add support for proxy setting for HTTP Client？for now,  classes in openai-php/client are all final，we can't extend them for customize

**Comment by nunomaduro** [comment]
Can you elaborate on what do you mean by "proxy setting"?

**Comment by seebyyu** [comment]
> Can you elaborate on what do you mean by "proxy setting"?

client [#73 ](https://github.com/openai-php/client/pull/73)
client-laravel [#25](https://github.com/openai-php/laravel/pull/25)

**Comment by wdwlrz** [comment]
OpenAI.php
line:29
$client = new GuzzleClient(['verify'=>false,'proxy'=>'http://127.0.0.1:7890']);
do like this.
兄弟，clash挂个流量订阅，然后开始玩耍吧。

**Comment by gehrisandro** [comment]
This can now be achieved by using the newly introduced factory:

```php
$client = OpenAI::factory()
    ->withApiKey('<your-api-key>')
    ->withHttpClient(new GuzzleClient(['verify'=>false,'proxy'=>'http://127.0.0.1:7890']))
    ->make();
```
