### ISSUE TITLE
Model gpt-3.5-turbo not matching settings in usage report

### ISSUE THREAD

**Issue by lucianotonet** [openai-php/client#76]
Hi 👋

I set up the OpenAI client to use the gpt-3.5-turbo model, however, in the [usage report](https://platform.openai.com/account/usage), it appears as **gpt-3.5-turbo-0301**.

![image](https://user-images.githubusercontent.com/2693019/225016317-6a140509-145d-4ea1-9a8d-fb6e0faaab5f.png)

My configurations are set to use gpt-3.5-turbo:
![image](https://user-images.githubusercontent.com/2693019/225017280-66f73556-6f13-4591-b0f5-1c92d3d1224d.png)

Although they are almost the same, the documentation states the following:
![image](https://user-images.githubusercontent.com/2693019/225019574-e278e486-51a2-40f6-b2d3-e74f0582b091.png)

In my tests, I noticed that it is really not following the system instructions.

I could not find the responsible part of the code to fix and submit a pull request, so how can we check that?

**Comment by genesiscz** [comment]
I think everybody who uses gpt-3.5-turbo now uses gpt-3.5-turbo-0301. gpt-3.5-turbo automatically always uses the most recent version which is 0301 in today's case.

**Comment by gehrisandro** [comment]
@genesiscz  I agree, this seem to be the intended behaviour and not an issue with the library.
