### ISSUE TITLE
Unable to mock anything due to everything being `final`

### ISSUE THREAD

**Issue by stevebauman** [openai-php/client#77]
Wanted to start with thanks a lot for this great package! Really appreciate the work you've done here. ❤️ 

---

I'm currently trying to mock responses from OpenAI, however this appears to not be easily done, because everything is marked `final`, which prevents mocking anything. This makes it a very painful developer experience when testing.

Maybe we can use a factory or something in the `OpenAI::client()` static method, and remove `final` on the `Client`, so it's at least possible to mock the client itself?

```php
final class OpenAIClientFactory
{
    public function make(string $apiToken, string $organization = null): Client
    {
        // ...
    }
}
```

```php
final class OpenAI
{
    /**
     * Creates a new Open AI Client with the given API token.
     */
    public static function client(string $apiToken, string $organization = null): Client
    {
        return app(OpenAIClientFactory::class)->make($apiToken, $organization);
    }
}
```

```php
$this->app->bind(OpenAIClientFactory::class);
```

```php
// TestCase

use OpenAI\Client;

$client = Mockery::mock(Client::class);

app()->bind(OpenAIClientFactory::class, function () use ($client) {
    $mock = Mockery::mock(OpenAIClientFactory::class);

    $mock->shouldRecieve('make')->andReturn($client);

    return $mock;
});

$client->shouldReceive('...')->andReturn('...');
```

Let me know your thoughts, thanks!

**Comment by stevebauman** [comment]
For others who are looking to do this as well, here is how I was able to work around the `final` classes.

> **Important**: You still cannot mock this libraries response classes due to them being `final`, so you cannot use strict return types on methods where you call the library. This guide is also assuming you're using a framework like Laravel with an IoC container.

First, create an `OpenAIClientProxy`. We will need this to be able to mock method calls on the client, and return our own responses. We can add a `@mixin` annotation so your IDE will know all the underlying `OpenAI\Client` methods:

```php
use Illuminate\Support\Traits\ForwardsCalls;
use OpenAI\Client;

/** @mixin \OpenAI\Client */
class OpenAIClientProxy
{
    use ForwardsCalls;

    /**
     * Constructor.
     */
    public function __construct(
        protected Client $client
    ) {
    }

    /**
     * Forward missing method calls onto the OpenAI client.
     */
    public function __call(string $method, array $parameters): mixed
    {
        return $this->forwardCallTo($this->client, $method, $parameters);
    }
}
```

Next, we'll make a factory class that will instantiate the `OpenAI` client and return the proxy. This factory will allow us to swap out the proxy with our own mocks:

```php
use OpenAI;

class OpenAIClientFactory
{
    /**
     * Make a new OpenAI client.
     */
    public function make(string $apiKey, string $organization = null): OpenAIClientProxy
    {
        return new OpenAIClientProxy(
            OpenAI::client($apiKey, $organization)
        );
    }
}
```

Now we can start mocking and testing:

```php
use Mockery;
use App\OpenAIClientProxy;
use App\OpenAIClientFactory;
use Illuminate\Support\Fluent;

public function test()
{
    $client = Mockery::mock(OpenAIClientProxy::class);

    $client->shouldReceive('completions->create')->andReturn(
        new Fluent([
            'choices' => [
                new Fluent(['text' => 'Some response text']),
            ],
        ])
    );

    app()->bind(OpenAIClientFactory::class, function () use ($client) {
        $mock = Mockery::mock(OpenAIClientFactory::class);

        $mock->shouldReceive('make')->andReturn($client);

        return $mock;
    });
    
    // Call something in your application to initiate the completion creation...
}
```

Somewhere in your application:

```php
$client = app(OpenAIClientFactory::class)->make($apiKey);

$response = $client->completions()->create(['...']);
```

**Comment by gehrisandro** [comment]
Hi @stevebauman 

Thank you for raising the issue.

We are currently working on improving the ability to test requests made through the library. There are two PRs, one for the client library and one for the Laravel wrapper if you are using the package with Laravel:
Client: https://github.com/openai-php/client/pull/71
Laravel: https://github.com/openai-php/laravel/pull/24

It basically follows the Laravel principals like `Mail::fake()` or `Http::fake()` on the facades.

There is no proper documentation yet but you can find examples in the tests:
https://github.com/openai-php/laravel/pull/24/files#diff-7eadda118164a5ffcbe854ac63bcfd6a8fe31e0d54528db63dd6a418a4c60ff5L4

Please let me know, if this approach would solve your testing issues.

**Comment by stevebauman** [comment]
Hi @gehrisandro,

Yes! Your PR would definitely resolve my testing issues. That’s fantastic. I hope it gets merged 👏

**Comment by alnutile** [comment]
@stevebauman I share a workaround here https://github.com/openai-php/laravel/issues/23#issuecomment-1499510702

**Comment by nunomaduro** [comment]
This will be fixed in tomorrow's release.
