### ISSUE TITLE
Using completion endpoint for paraphrasing

### ISSUE THREAD

**Issue by ahmedabbas1990** [openai-php/client#79]
How can I create a completion request that then return paraphrased variants of my given prompt?

**Comment by gehrisandro** [comment]
Hi @ahmedabbas1990 

This is the repository of a library to connect OpenAI. Therefore we do not provide support for the OpenAI functionality itself.

But you will find everything necessary in the official documentation: https://platform.openai.com/docs/guides/completion/introduction
