### ISSUE TITLE
Looking for a more complete example of stream responses.

### ISSUE THREAD

**Issue by scottfennell-toptal** [openai-php/client#94]
Hello, I see this example here:  https://github.com/openai-php/client#created-streamed

However, it would be helpful to see a more complete example that demonstrates how to integrate this into a web page.

For example, if we could get a demo that connects the dots to JS and HTML the way this MDN demo does, that would be perfect:

https://github.com/mdn/dom-examples/tree/main/server-sent-events

**Comment by gehrisandro** [comment]
@scottfennell-toptal If you would like to extend the documentation, feel free to PR.

If you are looking for help how to use this library in a specific context there is more information needed.
But in general, it depends highly on the framework you are using and what your goal is. If you are working with Laravel you can do something like that:
```php
Route::get('/completion-stream', function () {
    $client = OpenAI::client('*********');

    $stream = $client->completions()->createStreamed([
        'model' => 'text-davinci-003',
        'prompt' => 'PHP is ',
        'max_tokens' => 1000,
    ]);

    return response()->stream(
        function () use ($stream) {
            foreach($stream as $response){
                echo $response->choices[0]->text;
                ob_flush();
                flush();
            }
        },
        200,
        [
            'X-Accel-Buffering' => 'no',
        ]
    );
});
```

**Comment by debuggerone** [comment]
You got to understand that there is an output buffer. Depending on your webserver it may be needed to send a specific amount of data before it works.

Try to run this script to understand:


<?php

for($i=0;$i<10000;$i++) {
  echo '.';
  flush();
}

**Comment by strfic** [comment]
> @scottfennell-toptal If you would like to extend the documentation, feel free to PR.
> 
> If you are looking for help how to use this library in a specific context there is more information needed. But in general, it depends highly on the framework you are using and what your goal is. If you are working with Laravel you can do something like that:
> 
> ```
> Route::get('/completion-stream', function () {
>     $client = OpenAI::client('*********');
> 
>     $stream = $client->completions()->createStreamed([
>         'model' => 'text-davinci-003',
>         'prompt' => 'PHP is ',
>         'max_tokens' => 1000,
>     ]);
> 
>     return response()->stream(
>         function () use ($stream) {
>             foreach($stream as $response){
>                 echo $response->choices[0]->text;
>                 ob_flush();
>                 flush();
>             }
>         },
>         200,
>         [
>             'X-Accel-Buffering' => 'no',
>         ]
>     );
> });
> ```

How to do this in vanilla PHP? I tried following client side code but everything is displayed at once and not in streaming way:
`<html>
<body>
<div id="response"></div>
</body>

<script>
const xhr = new XMLHttpRequest();
const responseDiv = document.getElementById('response');

xhr.onreadystatechange = function() {
  if (xhr.readyState === XMLHttpRequest.LOADING || xhr.readyState === XMLHttpRequest.DONE) {
    responseDiv.innerHTML += xhr.responseText;
	console.log(xhr.responseText);
  }
};

xhr.open('GET', 'https://example.com/streamingcheck.php', true);
xhr.send();

</script>
</html>`

In streamingcheck.php
`$stream = $client->chat()->createStreamed([
			'model' => 'gpt-3.5-turbo',
			'messages'=> $messages,
			
		]);
	
	ob_start();
	//ob_implicit_flush(true);
	foreach($stream as $response)
	{
		$res = $response->choices[0]->toArray();
		var_dump($res);
		echo "<br/>";
		//ob_flush();
        		flush();
		usleep(250000);
	}
	ob_end_flush();
`
