### ISSUE TITLE
How to remember conversetion?

### ISSUE THREAD

**Issue by Akalanka1337** [openai-php/client#95]
how to remember whole conversation in like ChatGPT?

**Comment by debuggerone** [comment]
Create a knowledge graph, add a database, summarize older messages,... there are many ways to accomplish that.
What exactly do you want to do?

**Comment by Akalanka1337** [comment]
Currently, I'm passing my entire conversation to a new input, but it's costing me a lot. Therefore, I want to reduce the amount of data I'm passing.

- In my Laravel Applicaiton

**Comment by nunomaduro** [comment]
It's not possible to save context between OpenAI calls.

**Comment by debuggerone** [comment]
user: give me something
assistant: aaaaaaaaaaaaaaaaaaaaaaaaaaaa
user: nice and what about b?
assistant: bbbbbbbbbbbbbbbbbbbbbbbbbbbb

let's assumne you have reached the tokenlimit with that conversation.
Ask the api to summarize aaaaaaaaaaaaaaaaaaaaaaa which could be aaa...

Then you have 

user: give me something
assistant: aaa...
user: nice and what about b?
assistant: bbbbbbbbbbbbbbbbbbbbbbbbbbbb

And you can add more questions.

Also using special prompting techniques don't require you to keep the whole context always.
Work with a database.

**Comment by gborgonovo** [comment]
@debuggerone I'm interested in improving the way it keeps the context with openai-php/client, can you provide any link or docs to know more about possible approaches?
Thank you.
