### ISSUE TITLE
Unable to write tests as the "testing" directory isn't in the latest version

### ISSUE THREAD

**Issue by SebKay** [openai-php/client#96]
For some reason the `testing` directory is missing so I can't write any tests using the `OpenAI\Testing\ClientFake` class.

I've updated everything in my (Laravel) project to the latest version.

`openai-php/client` is using version `0.4.1`.

Screenshot attached to show what's being included.

![Screenshot 2023-04-05 at 13 09 02](https://user-images.githubusercontent.com/1873695/230076516-2d99116d-1988-48a5-9d6d-8148293e3b75.png)

Any help would be greatly appreciated!

Loving the package. Really helping me with some AI work. Thanks for all your hard work on it!

**Comment by nunomaduro** [comment]
The testing feature it's not released it.

**Comment by 0101coding** [comment]
I also saw the documentation on the testing feature, and after writing the test, I get class not found. Can you help to update the readme?

**Comment by nunomaduro** [comment]
@0101coding @dlakomski Are you using the v0.4 version?

**Comment by dlakomski** [comment]
Yes
